### ISSUE TITLE
🆕 Software Suggestion | Passepartout

### ISSUE THREAD

**Issue by nitrohorse** [privacytools/privacytools.io#1119]
## Basic Information

**Name:** Passepartout
**Category:** iOS OpenVPN client
**URL:** https://passepartoutvpn.app/
**Source Code:** https://github.com/passepartoutvpn (GPLv3)
**App Store link:** https://apps.apple.com/us/app/passepartout-openvpn-client/id1433648537
**Cost:** $2

## Description
> A non-official, user-friendly OpenVPN client for iOS (soon for macOS). Passepartout not only supports .ovpn configuration files, but also embeds presets for well-known VPN providers. Along with features like trusted networks and smart battery usage.

Note the developer used to previously work as [mobile tech lead @ PIA](https://davidederosa.com/resume/).

**Comment by blacklight447-ptio** [comment]
should we have an additional page for IOS apps, similar to android?

**Comment by Mikaela** [comment]
Android seems to only have a section on the operating systems page and I would be fine with adding similar for iOS to it.

**Comment by blacklight447-ptio** [comment]
would probbaly be appropriate.
