### ISSUE TITLE
🆕 Software Suggestion | Self-hostable analytics / why to not use Google Analytics / Matomo

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#1186]
This suggestion was given to me offline.

## Basic Information

**Name:** Matomo
**Category:** Website analytics
**URL:** https://matomo.org/

## Description

I am not very familiar with software for this, but I am aware that we have Matomo and I have also encountered it through another organisation.

For searchers, previously known as Piwik.

**Comment by Perelandra0x309** [comment]
Another option:
http://www.openwebanalytics.com/

**Comment by SimonVanacco** [comment]
Open Web Analytics is a cool piece of software, however it seems like it hasn't been updated for 14 months, which would lead me to believe it's not maintained anymore.

**Comment by Mikaela** [comment]
Example case where this page could be useful: https://github.com/ipfs/website/issues/332

**Comment by Mikaela** [comment]
https://webtransparency.cs.princeton.edu/webcensus/ via https://www.eff.org/deeplinks/2019/08/dont-play-googles-privacy-sandbox-1 possibly worth looking at

**Comment by Mikaela** [comment]
Assigning myself so I might sometime attempt this, but as always, PRs are always welcome.

**Comment by nitrohorse** [comment]
I remember Aral Balkan [posting this on his Mastodon account](https://mastodon.ar.al/@aral/101243902110497078) in December 2018. Not sure how Matomo has evolved since then but thought this was worth linking here for reference.

> No, @Matomo (previously Piwik) doesn’t give two shits about privacy; releases tag manager product, hints at first-party tag manager integration of third-party trackers as method for circumventing tracker blockers. https://matomo.org/blog/2018/12/matomo-tag-manager-out-of-beta-now-available/

**Comment by FreddyMarsden** [comment]
Also worth mentioning:
- https://plausible.io/
- https://posthog.com/
- https://goatcounter.com/
and #1871

**Comment by ph00lt0** [comment]
Now that Matomo is removed I think this can be closed as well https://github.com/privacytools/privacytools.io/pull/2013

**Comment by Mikaela** [comment]
I don't think the issues are that much related, while PrivacyTools may not have interest towards analytics anymore, that doesn't mean some othwr site would lose interest also and if there aren't any alternatives suggested, they may end up to Google Analytics.

**Comment by freddy-m** [comment]
After pondering over this for a while, I don't think analytics services are within the scope of the site. Hence, I'll be closing this issue.
