### ISSUE TITLE
Do our Android recommendations have to be in the official F-Droid repository?

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#1201]
This concern was rised in #1132 where I commented:

> I can understand the desire of having app in the official F-Droid repository as it helps with discoverability and is a confirmation that the app fulfils their recommendations, but I think decentralization is also worth thinking about and that it's not desirable for everything to be centralized only on the official F-Droid repo.

This issue also affects #1187 (& #1200) which aren't in the official F-Droid repository, but has its own repository. I think we also list Bitwarden that is in the same situation.

See also: #338.

**Comment by blacklight447-ptio** [comment]
First of all, we would need to decide whether this only cover the official f-droid repo, or being installable from any fdroid all repo. 

In any case though, while I would see being on fdroid is a big bonus, I would not make it a requirement, as it would have the potentional to exclude some really good apps just for not being on fdroid.

**Comment by Mikaela** [comment]
Judging by the three :+1: to the previous comment, I guess our policy which just needs committing, is:

> The app doesn't need to be in the official f-droid repo, but it's a plus.

@privacytoolsIO/editorial further thoughts?

**Comment by dngray** [comment]
F-Droid is a distribution mechanism.

> thinking about and that it's not desirable for everything to be centralized only on the official F-Droid repo.

Technically it isn't centralized. There are f-droid mirrors.

The advantage of being in the official F-droid repository is that it must be open source and able to be built from that source.

There is the [reproducible builds](https://www.f-droid.org/en/2019/05/05/trust-privacy-and-free-software.html) initiative. It is more desirable for the software to be in F-Droid and reproducible than in a third party repository and not be reproducible. You can see the [recent builds from their wiki](https://f-droid.org/wiki/page/Main_Page).

- https://f-droid.org/en/docs/Build_Server_Setup/
- https://en.wikipedia.org/wiki/Deterministic_compilation
- https://reproducible-builds.org/

Also note that with Google Play, [Google can push updates to you](https://drewdevault.com/2018/08/08/Signal.html), whenever they want. Could select targets get a certain update that nobody else gets? Sure, you've got a set of login credentials attached to that software distribution center.
