### ISSUE TITLE
🌐 Website Issue | Decentraleyes requires configuration on Chromium based browsers when HTTPS Everywhere is used

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#1326]
## Description

> Decentraleyes emulates Content Delivery Networks locally by intercepting requests, finding the required resource and injecting it into the environment. This all happens instantaneously, automatically, and no prior configuration is required.

* https://www.privacytools.io/browsers/#addons

In reality when Chromium is used with HTTPS Everywhere, the user must go to https://decentraleyes.org/configure-https-everywhere/ and disable HTTPS Everywhere for the content loaded by it so that Decentraleyes can redirect the requests into itself.

Unrelated note of future interest: IPFS Companion (listed under self-contained networks) wishes to be able to replace Decentraleyes in the future: https://github.com/ipfs-shipyard/ipfs-companion/issues/674.

**Comment by DF2NwasJiMYLNFyAOQarZtfPPj0qXh4G** [comment]
Also worth mentioning that [Decentraleyes doesn't work out-of-the-box if a blocker such as uBO, uM, or NoScript is being used](https://git.synz.io/Synzvato/decentraleyes/wikis/Frequently-Asked-Questions#for-umatrix-and-ublock-origin-non-easy-mode-users).*

\* uBO is fine if it's on Easy mode (default) or looser settings. Decentraleyes requires Scripts/XHR to function.

**Comment by Mikaela** [comment]
Also related: https://github.com/privacytoolsIO/privacytools.io/issues/1292#issuecomment-530239422 . I am going to open a meta issue to stay on track of these.

**Comment by dngray** [comment]
It requires configuration everywhere, including on Firefox when ublock is used.

We're thinking of removing it as per https://github.com/privacytools/privacytools.io/pull/2005#issuecomment-704006090
