### ISSUE TITLE
❌ Software Removal | jQuery

### ISSUE THREAD

**Issue by dawidpotocki** [privacytools/privacytools.io#1356]
jQuery is a JavaScript library, which is a dependency for Bootstrap 4, but I
don't think we actually need it for anything we do on our website
https://getbootstrap.com/docs/4.3/getting-started/introduction/#js.
Having additional library that has no use, doesn't make any sense. AFAIK, it
is only needed for one thing in `main.js`, but we should be easily able to
rewrite that in Vanilla JS.

**Comment by nitrohorse** [comment]
Great idea :+1:

**Comment by zenithium** [comment]
Bump @dawidpotocki
