### ISSUE TITLE
🆕 Software Suggestion | Crypton.sh

### ISSUE THREAD

**Issue by hugecheese** [privacytools/privacytools.io#1475]
## Basic Information

**Name:** Crypton.sh
**Category:** Phone Numbers (new category?)
**URL:** https://crypton.sh

## Description
[reddit thread](https://www.reddit.com/r/privacytoolsIO/comments/dtihu2/any_service_paid_or_free_to_buy_permanent/)

**Comment by sakura974201** [comment]
This is good.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I think they are the best ones offering that kind of service, but still, I would back up until some other providers appear or until we can find some kind of criteria to measure how secure this is. Also, a warning should be added to only use Monero if what you are seeking is anonymity.

**Comment by sakura974201** [comment]
Signal requires a phone number to register.
If you recommend Signal, your SMS provider should also mention it.

**Comment by blacklight447-ptio** [comment]
hmm, we would need to figuire out what  kind of category this would belong under.

**Comment by FreddyMarsden** [comment]
#1868 is also relevant and seems to be a better product.

**Comment by lynn-stephenson** [comment]
@freddy-m Close this.

**Comment by zero77** [comment]
@lynn-stephenson @freddy-m 
Could we not add a new phone number category.
Especially as some services such as signal require the user to have a phone number.

**Comment by freddy-m** [comment]
Sorry for not noticing your message @lynn-stephenson 😞
