### ISSUE TITLE
✨ Feature Suggestion | Section about post-quantum cryptography

### ISSUE THREAD

**Issue by GrimPixel** [privacytools/privacytools.io#1477]
## Description:

Add a section about information about post-quantum cryptography, because current cryptography can be easily decrypted by quantum computers in the near future, the earlier to be prepared, the better.

https://en.wikipedia.org/wiki/Quantum_cryptography
https://en.wikipedia.org/wiki/Post-quantum_cryptography

**Comment by dngray** [comment]
Until we start to see mainstream frameworks and suites (eg TLS) including support there's not going to be software that actually uses it.

As of yet there haven't been any quantum computers flexible enough and with enough qubits for this to be a concern though that may not be the case in 10 years time. Those which do exist are still at a research prototype phase in laboratories.

#### October 2019
- [Here’s what the people who claimed Google’s quantum supremacy have to say about it (ArsTechnica)](https://arstechnica.com/science/2019/10/inside-googles-quantum-computing-efforts/)
- [Quantum supremacy and post-quantum crypto](https://www.johndcook.com/blog/2019/10/23/quantum-supremacy-and-pqc/)

#### April 2018
- [Post-quantum confidentiality for TLS](https://www.imperialviolet.org/2018/04/11/pqconftls.html)

**Comment by Frichetten** [comment]
I agree with @dngray that we are unlikely to see quantum computing be a threat to encryption in the very near future, but for what it's worth there has been some development of post quantum implementations of TLS. AWS actually just released one [Post-quantum TLS now Supported in AWS KMS](https://aws.amazon.com/blogs/security/post-quantum-tls-now-supported-in-aws-kms/)

**Comment by dngray** [comment]
Microsoft's [Post-quantum Cryptography](https://www.microsoft.com/en-us/research/project/post-quantum-cryptography/) has a number of experimental implementations listed:

A fork of OpenVPN, OpenSSL and OpenSSH:

- [Post-Quantum Crypto VPN](https://www.microsoft.com/en-us/research/project/post-quantum-crypto-vpn)
- [Post-Quantum TLS](https://www.microsoft.com/en-us/research/project/post-quantum-tls/)
- [Post-Quantum SSH](https://www.microsoft.com/en-us/research/project/post-quantum-ssh/)

**Comment by dngray** [comment]
#### July 2020

[NIST’s Post-Quantum Cryptography Program Enters ‘Selection Round’](https://www.nist.gov/news-events/news/2020/07/nists-post-quantum-cryptography-program-enters-selection-round)

**Comment by blacklight447-ptio** [comment]
In any case, till any post quantum encryption becomes standardised, I don't see the point of including stuff about it on the website, as everything can still be subject to major change. I am going to close this issue (for now).
