### ISSUE TITLE
🆕 Software Suggestion | Zulip (team chat)

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#1495]
## Basic Information

**Name:** Zulip
**Category:** Team chat
**URL:** https://zulip.org/ / https://github.com/zulip

## Description

Memtioned in https://github.com/privacytoolsIO/privacytools.io/issues/999#issuecomment-504277267, but not acted upon.

**Comment by foresto** [comment]
As far as I can tell, Zulip lacks end-to-end encryption. (Their security features are [listed here](https://zulipchat.com/security/).) That puts it at quite a disadvantage vs. other tools where privacy is concerned.

**Comment by lynn-stephenson** [comment]
There doesn't appear to be any reason to choose this over other alt software. I'm down for closing this.

It only has basic security features, nothing noteworthy. Basically it's an open source Slack. ;P
