### ISSUE TITLE
🆕 Software Suggestion | Evolution Mail

### ISSUE THREAD

**Issue by cvandesande** [privacytools/privacytools.io#1643]
## Basic Information

Name: Evolution Mail
Category: Email Software
URL: https://wiki.gnome.org/Apps/Evolution

## Description
One of the oldest and still regularly developed email clients for Linux. Feels like this should have been a recommend app for a long time.

**Comment by dngray** [comment]
The only issue with adding this, is we really then should also add [KMail](https://userbase.kde.org/KMail) as well.

Unfortunately these things aren't really portable to Windows, MacOS etc.

**Comment by blacklight447-ptio** [comment]
well we currently don't really require cross platform do we?
