### ISSUE TITLE
🌐 Website Issue | New email clients page

### ISSUE THREAD

**Issue by dngray** [privacytools/privacytools.io#1707]
After https://github.com/privacytoolsIO/privacytools.io/pull/1672 is complete I want to improve the email clients page.

I think for a start we should split the recommendations by platform. A criteria should exist that only allows email clients that support OpenPGP.

Closes: https://github.com/privacytoolsIO/privacytools.io/issues/1643
Closes: https://github.com/privacytools/privacytools.io/issues/2072

**Comment by blacklight447-ptio** [comment]
So it should be similar to our browser section?

**Comment by dngray** [comment]
I was more thinking of a tidyup, eg removing Torbirdy as it's no longer supported etc.

Splitting the "Privacy Email Tools" so testing tools are under "Testing tools". Maybe we could do our own OpenPGP tutorial, ie https://github.com/privacytoolsIO/privacytools.io/issues/1725 first.

**Comment by blacklight447-ptio** [comment]
We could do both, one section with clients for all platforms like the browser section, and below that we list email testing tools and maybe link to a blog post with a openpgp tutorial.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Enigmail should be delisted too as Thunderbird will add its own support for OpenPGP and it's going to be discontinued this year.

https://blog.thunderbird.net/2019/10/thunderbird-enigmail-and-openpgp/

>The Enigmail Add-on has made it possible to use Thunderbird with external GnuPG software for OpenPGP messaging. Because the types of add-ons supported in Thunderbird will change with version 78, the current Thunderbird 68.x branch (maintained until Fall 2020) will be the last that can be used with Enigmail.

**Comment by Mikaela** [comment]
I would wait for the Thunderbird version with it's own OpenPGP implementation to be released and at least the biggest distributions to remove Enigmail from their repositories in favour of it first.

**Comment by FreddyMarsden** [comment]
[Mailpile](https://www.mailpile.is/) is currently under worth mentioning, though I feel as if it should be given its own card. Heres what the new layout could look like:

### Desktop Email Clients:

- Thunderbird
- Mailpile
- Claws-Mail

### Mobile Email Clients:

- K-9 Mail
- FariMail

Other clients to think about could be stuff like [notmuchmail](https://notmuchmail.org/) or [aerc](https://aerc-mail.org/) though they don't necessarily focus on privacy.

**Comment by dngray** [comment]
I think this would be good. To be honest though I'm thinking we might scrap Claws Mail, their latest stable still is not GTK3. In a [month or so](https://wiki.mozilla.org/Thunderbird:Home#Releases) we should be also seeing [Thunderbird 78](https://wiki.mozilla.org/Release_Management/Calendar), we can then scrap Enigmail, which simplifies things a bit.

**Comment by FreddyMarsden** [comment]
Yeah, I've no experience with Claws personally, just didn't want to delist anything for no reason. I can submit a PR if you would like.

**Comment by dngray** [comment]
Sure a PR would be welcome.
