### ISSUE TITLE
❌ Software Removal | Soverin Email Provider

### ISSUE THREAD

**Issue by Zenithium** [privacytools/privacytools.io#1759]
## Description

Soverin requires disclosing a phone number on registration.

## Why I am making the suggestion

This is against the criteria:
- "Don't require personally identifiable information (PII) besides username and password."

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Mmm, this is some big shit. I wonder if sending an e-mail to them may do something to change this.

**Comment by zenithium** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe @dngray said he would mail them to see what can be done about this but I doubt anything will come of it. The phone number requirement is spread all throughout their policies and by their wording they seem to consider it essential for providing the service. Hoping that they resolve this though, supposedly they require it for password recovery but it seems like a nonsense half-truth. One other reason would be spam prevention but the service is already pay-to-use so I don't see any reason why they need a phone number as mandatory for registration.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I think they deserve to be delisted if they won't change that, CTemplar is going to be added soon (I think) and there are quite a few providers that even give you free tiers, so I don't think they deserve it, if you keep in mind that most SIM cards are literally tied to you ID.

**Comment by dngray** [comment]
I've sent them an email, we'll see if we can get some more details.

**Comment by blacklight447-ptio** [comment]
@dngray  Any word from them so far?

**Comment by dngray** [comment]
I sent them a follow up reply, I guess we will see where it goes.

I'm happy to be lenient for the time being given the state of the world at the moment.

**Comment by dngray** [comment]
I did get a reply, apparently they are "looking into it".

**Comment by fabianski7** [comment]
up

**Comment by blacklight447-ptio** [comment]
@dngray  any updates?

**Comment by dngray** [comment]
> @dngray any updates?

Unfortunately no, they haven't gotten back to me since before. I will poke them again on this.
