### ISSUE TITLE
🆕 Software Suggestion | Consider replacing DecentralEyes with LocalCDN?

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#1779]
## Basic Information

**Name:** LocalCDN
**Category:** Browser extensions
**URL:** https://gitlab.com/nobody42/localcdn

## Description

Fork of Decentraleyes with more maintenance.

## Why I am making the suggestion

#1328, Decentraleyes appears unmaintained while LocalCDN is and to quote @nitrohorse from Reddit:

> A couple of interesting things worth noting:

>     Decentraleyes has the advantage of being a "recommended" webextension which "undergoes a thorough technical security review to ensure it adheres to Mozilla’s add-on policies."

>     Decentraleyes' has public ownership; Thomas Reintjes.

>     Decentraleyes' last commit and last activity by the maintainer was 4 months ago; there are 78 open issues, and 9 merge requests with no indication of being merged in anytime soon. So I assume LocalCDN was forked because Decentraleyes actually appears stale which is unfortunate.

>     LocalCDN doesn't have public ownership.

>     LocalCDN isn't a recommended webextension and thus updates won't undergo "thorough technical security reviews."

>     LocalCDN does support more assets/CDNs (which increases privacy beyond Decentraleyes) and will support more.

>     LocalCDN has not slipped a new permission in. Compare LocalCDN's manifest.json with Decentraleyes'.

> Overall LocalCDN appears to increase privacy (more CDN/asset support) but at the cost of some security (no technical security reviews by Mozilla).

* https://www.reddit.com/r/privacytoolsIO/comments/fc05uh/just_found_out_about_firefox_addon_localcdn_fork/fj836n1/ (has nicer formatting and source links)

## My connection with the software

I am trying it out of curiosity since today learning it has µMatrix ruleset generator.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by blacklight447-ptio** [comment]
This has been on my eye for a while as well, but decentraleyes is a well known and respected project, so  directly replacing it seems a bit to quick imo.

**Comment by hugoncosta** [comment]
I'd suggest starting out as a "worth mention" and visit this in a few weeks/months, see if Decentraleyes goes back to normal development. Should that not happen, we'd probably go ahead and either switch their places or remove Decentraleyes completly.

That got me thinking, should we have some page where these listings/de-listings are accounted for? Something along the lines of a mailing list, RSS-able, where we'd get either a week/month-ly digest or a direct warning as soon as something was changed. I could certainly see the use case for sending out a warning in a case like [startpage's acquisition by Privacy One Group](https://blog.privacytools.io/delisting-startpage/).

**Comment by smnthermes** [comment]
What is the need of using both `>` and ` `` ` ?

**Comment by blacklight447-ptio** [comment]
we have had the idea of a newsletter come up before, but so far, we didn't have someone with the time on there hands to maintain such a thing. we would still like to do a  "this week in privacytools" in the future though.

in anyway, a worth mentioning might be a good solution for now, but i would have to look into the application myself first.

**Comment by Mikaela** [comment]
There was a question on weird formatting, the answer is that I have just quoted everything and GitHub has decided to parse it weirdly. I don't have motivation to fix it and when I would have time I keep forgetting it. Here is the raw message if anyone wants to improve:

```
## Basic Information

**Name:** LocalCDN
**Category:** Browser extensions
**URL:** https://gitlab.com/nobody42/localcdn

## Description

Fork of Decentraleyes with more maintenance.


## Why I am making the suggestion

#1328, Decentraleyes appears unmaintained while LocalCDN is and to quote @nitrohorse from Reddit:

> A couple of interesting things worth noting:

>     Decentraleyes has the advantage of being a "recommended" webextension which "undergoes a thorough technical security review to ensure it adheres to Mozilla’s add-on policies."

>     Decentraleyes' has public ownership; Thomas Reintjes.

>     Decentraleyes' last commit and last activity by the maintainer was 4 months ago; there are 78 open issues, and 9 merge requests with no indication of being merged in anytime soon. So I assume LocalCDN was forked because Decentraleyes actually appears stale which is unfortunate.

>     LocalCDN doesn't have public ownership.

>     LocalCDN isn't a recommended webextension and thus updates won't undergo "thorough technical security reviews."

>     LocalCDN does support more assets/CDNs (which increases privacy beyond Decentraleyes) and will support more.

>     LocalCDN has not slipped a new permission in. Compare LocalCDN's manifest.json with Decentraleyes'.

> Overall LocalCDN appears to increase privacy (more CDN/asset support) but at the cost of some security (no technical security reviews by Mozilla).

* https://www.reddit.com/r/privacytoolsIO/comments/fc05uh/just_found_out_about_firefox_addon_localcdn_fork/fj836n1/ (has nicer formatting and source links)

## My connection with the software

I am trying it out of curiosity since today learning it has µMatrix ruleset generator.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.
```

Self-marking as offtopic.

**Comment by lrq3000** [comment]
I agree with a Worth Mentioning until the project gets more recognition.

**Comment by blacklight447-ptio** [comment]
hey @lrq3000  would you be willing to shoot a PR for this?

**Comment by lrq3000** [comment]
Yes @blacklight447-ptio , sorry for the delay, the PR is realy :-)

**Comment by blacklight447-ptio** [comment]
btw: seems like the decentraleyes got an update on 30 april

**Comment by dngray** [comment]
It's also worth noting that LocalCDN does not work on Android (Fenix builds) while Decentraleyes does presently.

**Comment by maniusq** [comment]
> It's also worth noting that LocalCDN does not work on Android (Fenix builds)

This is probably dependent on Mozilla, see here: https://codeberg.org/nobody/LocalCDN/wiki#user-content-13-can-i-use-localcdn-in-firefox-for-android-fenix

I think both addons can be recommended. DecentralEyes for beginners and LocalCDN for advanced users. Similar to uBlock easy and medium/hard mode.

**Comment by dngray** [comment]
> I think both addons can be recommended. DecentralEyes for beginners and LocalCDN for advanced users. Similar to uBlock easy and medium/hard mode.

This certainly **won't** be happening. Decentraleyes does not actually work meaningfully therefore it won't be recommended: https://github.com/privacytools/privacytools.io/pull/2081#issuecomment-705996933
