### ISSUE TITLE
🆕 Software Suggestion | DTMF.io

### ISSUE THREAD

**Issue by ghost** [privacytools/privacytools.io#1868]
## Basic Information

**Name:** DTMF.io
**Category:** ??? (New category?)
**URL:** https://dtmf.io/

## Description
DTMF.io is a telephone number distributor.

## Why I am making the suggestion
It is useful when using Signal.

https://www.hardenize.com/report/dtmf.io/1588249575
https://www.ssllabs.com/ssltest/analyze.html?d=dtmf.io

## My connection with the software
I have no connection with them.

- [*] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by FreddyMarsden** [comment]
Maybe put it the worth mentioning section of the communications page. There was a big clean-up recently though...
