### ISSUE TITLE
🆕 Software Suggestion | Fathom Analytics

### ISSUE THREAD

**Issue by bcye** [privacytools/privacytools.io#1871]
## Basic Information

**Name:** Fathom
**Category:** Providers (Hosting? There isn't really a category for it)
**URL:** https://usefathom.com

## Description
Fathom is an analytics company that respects the privacy of website user and doesn't use cookies. [They document extensively and are transparent about how they track metrics](https://usefathom.com/blog/anonymization) [and another link on exactly what they collect from the visitors](https://usefathom.com/data). Besides privacy, their other selling point is simplicity, as they allow website providers to see all metrics on one page. They collect metrics like unique pageviews, pageviews, bounce rate (people who did not view more than one page), country, browser, referring website and time spend on the site. [They offer a free version that is open source](https://github.com/usefathom/fathom) and plan to open source their updates to the newer hosted and paid version later, although they haven't specified a date when that is going to happen

## Why I am making the suggestion
n/a

## My connection with the software
I really like what they're doing, but I am not affiliated with them.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by FreddyMarsden** [comment]
They aren't open source and haven't yet been audited yet, they are planning on getting audited in the future.
Other analytics that could be worth looking into are plausible.io and posthog.com.

**Comment by bcye** [comment]
@FreddyMarsden Yes they are. As I noted in the issue, they plan to open source the paid version later, but their free version is open source (the reasoning behind this is to give an incentive to upgrade): https://github.com/usefathom/fathom

**Comment by bcye** [comment]
Another one might be simpleanalytics.com, but as far as I know, they're the only open source option in the space.

**Comment by FreddyMarsden** [comment]
@byce thats the lite version, there are still proprietary parts. I sent them an email, I'll quote the response:
> Open-source doesn't ensure the privacy practices of a service. You could "open-source" your code but run something different in production. It's a virtue signal.
>We track zero user data, keep zero logs (heck, we don't even put raw request data into our queued jobs, it is discarded during the initial request). We go to incredible lengths, and that's why we're the leading privacy-focused analytics platform (by far).
>Anyway, we appreciate your email. One of the things we'd love to do in the future is have independent audits.

**Comment by bcye** [comment]
Still the lite version could be added to privacytools, as it is fully open source, couldn't it?
There are other services like Cryptomator on privacytools, that also have proprietary parts.

**Comment by LongJohn-Silver** [comment]
Matomo and GoatCounter and there are like 2 or 3 other services are FLOSS.

**Comment by danarel** [comment]
Actually, there is Plausible Analytics that is fully open source

https://plausible.io/

**Comment by bcye** [comment]
> Actually, there is Plausible Analytics that is fully open source
> 
> https://plausible.io/

But with that we are back where we started with Fathom, you can't verify the same code is running on their paid version.

**Comment by FreddyMarsden** [comment]
It's fully open source, and there is no free version.

**Comment by bcye** [comment]
> Open-source doesn't ensure the privacy practices of a service. You could "open-source" your code but run something different in production. It's a virtue signal.
@FreddyMarsden this applies as well to plausible, doesn't it?
With "paid" version I mean there hosted version instead of spinning up an instance yourself.

**Comment by FreddyMarsden** [comment]
I get that, but then we can screw all open source software and say that only audited software is any good. Though thats not the case.
Plausible is open about their ownership, if you don't trust them its fine. I'd rather use something thats fully open source and hasn't been audited than something that isn't open source and hasn't been audited.

**Comment by bcye** [comment]
I dislike the argument to, but it's equally valid in both cases. If that's holding us back we should only recommend installing the "open source" versions of either of them.

**Comment by ukutaht** [comment]
Author of the Plausible codebase here.

I agree with the sentiments here. Hosted services will always be a problem if you don't trust the provider. Even if i gave you ssh access to verify the code on my production machine, how do you know that I'm not running a proxy in front of it that pipes all requests to `/dev/evil`?

On the other hand, I believe that to have the biggest impact in this space (getting people off Google Analytics), we need good hosted services. It's more convenient, and a centralized service is much more resource-efficient in this space. Just my 2 cents.

I do want to offer a self-hosted version of Plausible once it's more stable. To illustrate, I'm currently integrating a branch that introduces a new database dependency and completely changes the hosting requirements, as well as monitoring, managing upgrades etc. The product is changing so fast that I'm worried it will slow things down significantly if I start offering quality support for people who want to self-host it.

For now, the code is released under the MIT license so you can take it and run it. I can assure you that I'm running the [stable branch](https://github.com/plausible-insights/plausible/tree/stable) of the repository in production, configured to deploy on push. The name of the branch is a bit of a misnomer given the rapid changes I'm making at the moment :)

**Comment by freddy-m** [comment]
@privacytools/editorial I don't think this (and analyitcs as a whole) really fits whitin the scope of the site, personally.

**Comment by freddy-m** [comment]
Closed because of #2205
