### ISSUE TITLE
❌ Software Removal | Keybase/KBFS acquired by Zoom

### ISSUE THREAD

**Issue by ph00lt0** [privacytools/privacytools.io#1894]
## Description

I know that it just was been added a few days ago but just this entered my feed: https://twitter.com/malgorithms/status/1258386143470653441

## Why I am making the suggestion

Keybase has been acquired by Zoom.  https://keybase.io/blog/keybase-joins-zoom
Zoom is terrible when it comes to privacy. They have been taking measures to ensure security but their privacy policy still leaves a lot of mysteries. 

## My connection with the software

I have no affiliation with Zoom or Keybase. I have been working on file sharing systems in the past for another vendor. 

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by JanOstrowka** [comment]
I would [add disclaimer](https://github.com/privacytoolsIO/privacytools.io/issues/1895) to the [software website](https://www.privacytools.io/software/real-time-communication/)

**Comment by ph00lt0** [comment]
@JanOstrowka I see now that also Keybase it self is listed under https://www.privacytools.io/software/real-time-communication/ 
That one should probably also be removed.

**Comment by dngray** [comment]
At this point I don't think we will do any removals as nobody really knows where it's going. We will wait and see how this pans out.

**Comment by ph00lt0** [comment]
I would say that we have seen that we cannot trust Zoom when it comes to privacy. As @danarel mentioned on the other issue Keybase has been very vague on the future.
The amount of info that Keybase has on it's users is very worrying and I would recommend everyone to leave it asap. You can always rejoin if something seems to be okay, but it is not heading this direction.

**Comment by dngray** [comment]
> I would say that we have seen that we cannot trust Zoom when it comes to privacy.

Zoom is not keybase, they are two different products.

> @danarel mentioned on the other issue Keybase has been very vague on the future.

Nobody knows, not even the company.

> The amount of info that Keybase has on it's users is very worrying and I would recommend everyone to leave it asap.

Not any more information that they didn't already have.

> You can always rejoin if something seems to be okay, but it is not heading this direction.

Likewise, you don't know if things will get worse.

**Comment by danarel** [comment]
> At this point I don't think we will do any removals as nobody really knows where it's going. We will wait and see how this pans out. It isn't like keybase has announced they're shutting down, nor has it been announced that it will not be developed in parallel with Zoom.

And I agree with this. We don't know much right now and I have a list of concerns but don't want to jump to a knee-jerk reaction. I think we can be cautious, slightly optimistic, but ready to remove once we learn more.

**Comment by ph00lt0** [comment]
I was expecting to open this discussion. The company could have made an agreement on keeping Keybase open source for example and i think that is a missed opportunity. I am very happy that Zoom started to take it's security seriously, hopefully privacy is the next step. Keybase is now in control of a company with a very bad reputation and I think recommending it therefore is an issue as long as it's not clear what will happen. I also understand that removing them now would have impact but in the world of privacy and security, their is no such thing as benefit of the doubt in my opinion.

**Comment by FreddyMarsden** [comment]
If we wanted alternatives keys.pub could be interesting.

**Comment by filips123** [comment]
It is probably not necessary to remove Keybase immediately, at least until more things are clear. But it would probably be good to mark it with an additional warning and/or put it on lower positions on page.

**Comment by DirkAmiably3829** [comment]
It's closed source server.
I agree with the removal.

**Comment by ata-star** [comment]
We should wait a bit
https://github.com/keybase/client/issues/24105

**Comment by dngray** [comment]
> It's closed source server.

> keybase/client#24105

The thing is, open source wouldn't really make it a lot better. Keybase is not federated so you'd still have individual pods that can't communicate with each other.

I don't imagine that would be much use for anyone outside of an organization. Retro-fitting federation into a protocol is virtually impossible and really needs to be something thought out from the beginning.

**Comment by danarel** [comment]
Also, this is just a call from users to open source it, not a statement by Keybase or Zoom saying they will. 

There's not reason to believe that Zoom purchased Keybase and would then just open source it.

**Comment by subsys-R9boq8** [comment]
I suggest we do a thorough background check of Zoom, since now Zoom is the background of Keybase.

**Comment by metryy** [comment]
Is Keybase not fundamentally designed to not trust their servers from the client? I don't really see the problem with the acquisition; in fact, this is pretty good news for Zoom since Keybase is developed by highly respected people in the crypto industry so security will improve  for a huge amount of people. The only real problem I see is that Zoom could lose interest in Keybase and shut it down.

**Comment by danarel** [comment]
The new CEO of Keybase (Zoom CEO) openly wants to work with FBI and other agencies.

https://techcrunch.com/2020/06/03/zooms-privacy-premium/

> “Free users for sure we don’t want to give [e2e encryption] because we also want to work together with FBI, with local law enforcement in case some people use Zoom for a bad purpose,” Yuan said on the call.

**Comment by blacklight447-ptio** [comment]
That did it for me too, i vote for removal.

**Comment by danarel** [comment]
My vote is for removal as well

**Comment by nitrohorse** [comment]
Another vote for removal.

**Comment by subsys-R9boq8** [comment]
The CEO of Zoom clearly stated:

1. his intention to cooperate with the FBI
2.the unwilling to protect users' privacy
3.the urge for more money

No **trust** can and shall be given to such guys that owns Keybase. I'm voting for removal.

**Comment by ph00lt0** [comment]
Zoom censored activists after request from Chinese government:

https://in.reuters.com/article/zoom-video-commn-privacy-idINKBN23J08S

**Comment by subsys-R9boq8** [comment]
News:

https://www.theguardian.com/technology/2020/jun/11/zoom-shuts-account-of-us-based-rights-group-after-tiananmen-anniversary-meeting

Zoom's own blog about this:

https://blog.zoom.us/wordpress/2020/06/11/improving-our-policies-as-we-continue-to-enable-global-collaboration/

In this blog, Zoom writes:

>Zoom is developing technology over the next several days that will enable us to remove or block at the participant level based on geography. This will enable us to comply with requests from local authorities when they determine activity on our platform is illegal within their borders; however, we will also be able to protect these conversations for participants outside of those borders where the activity is allowed.

No, if that's the company that owns KeyBase, I won't use it, forever. Now it's possible for Zoom to take down meetings based on local authorities' order (without even considering whether the request is proper or not, by themselves), after some time the same thing will happen on KeyBase users, too.

**Comment by rowan8k** [comment]
Considering Zoom's actions regarding privacy, oppressing freedom of speech by blocking users from holding online events about the 1989 Tiananmen Square protests and the intention to cooperate with parties that have proven to invade privacy like China, the FBI and other agencies I would say the acquisition of Keybase to be questionable regarding privacy concerns and thus not belonging on privacytools.io.

**Comment by dngray** [comment]
It's worth noting all these articles are about Zoom, not Keybase where everything is E2EE anyway (even for free users).

**Comment by subsys-R9boq8** [comment]
> 
> 
> It's worth noting all these articles are about Zoom

All these articles are about Zoom's leaders, which now became Keybase' leaders, too.

>
>everything is E2EE anyway (even for free users).

Not for metadata like login time and IP, which is quite easy if Keybase leaders decided to forbid some Chinese activists or someone else from using this service anymore based on FBI and local authorities. You have seen what happened to those activists who uses Zoom, why can't they replicate it on Keybase? At least it seems to me that **Zoom leaders are quite willing to cooperate with gov. authorities.**

**Comment by danarel** [comment]
While the articles are about Zoom, they reveal the companies open willingness to work with federal authorities and because they own Keybase, there is no reason to think that doesn’t apply to them as well. 

A willingness to work with authorities within the confines of the law is one thing, a willingness to not allow users total privacy and security so that you can more easily work with the feds is another.

**Comment by blacklight447-ptio** [comment]
ill make a PR to remove keybase.

**Comment by ph00lt0** [comment]
I know this issue is now sort of done with the pull request but I just got my eyes on this article:
https://theintercept.com/2020/04/03/zooms-encryption-is-not-suited-for-secrets-and-has-surprising-links-to-china-researchers-discover/

I thought you mind find it interesting.

**Comment by dngray** [comment]
That article is outdated, they use GCM mode now in zoom 5 apparently.

**Comment by ph00lt0** [comment]
@dngray it was more about the fact that thy actually cooperated and also have links.

**Comment by dngray** [comment]
heh. https://blog.zoom.us/wordpress/2020/06/17/end-to-end-encryption-update/

My guess is that there would have been people at Keybase who were opposed to the "think of the children" argument for making it a paid-only feature.
