### ISSUE TITLE
🆕 Software Suggestion | prgmr.com

### ISSUE THREAD

**Issue by FreddyMarsden** [privacytools/privacytools.io#1897]
## Basic Information

**Name:** prgmr.com
**Category:** Hosting
**URL:** [prgmr.com](https://prgmr.com/xen/)

## Description

Linux and BSD virtual servers.

- IPv6 subnet free upon request
- Credit card (via PayPal/Square), PayPal, Bitcoin, and check accepted
- [Public-facing leadership or ownership.](https://prgmr.com/about.html)
- 0 third party trackers

## Why I am making the suggestion

Noticed that they were used by [lobste.rs](https://lobste.rs/) so decided to check them out.

## My connection with the software

None.

- [ x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by DirkAmiably3829** [comment]
That's dangerous.
https://www.hardenize.com/report/prgmr.com/1589264368#email_tls
