### ISSUE TITLE
❌ Software Removal | Parabola GNU/Linux-libre

### ISSUE THREAD

**Issue by DirkAmiably3829** [privacytools/privacytools.io#1909]
## Description

We suggest removing Parabora's mention from Arch Linux in the PC Operating Systems category.

## Why I am making the suggestion
It is not properly maintained.
For example, it is still for asp utility Arch and doesn't work properly because it is not patched for Parabola.

The documentation is also unmaintained.
Even if Parabola OpenRC is installed according to the Installation Guide of the official Wiki, it does not boot normally.
This is because the package repository is not maintained.
https://wiki.parabola.nu/Installation_Guide

## My connection with the software
I don't have a connection with it.

- [*] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
Going to close this as it will be sorted with https://github.com/privacytools/privacytools.io/issues/1376#issuecomment-624275363

That's what we're currently looking at recommending.
