### ISSUE TITLE
📝 Correction | ProtonVPN link to FDroid not working

### ISSUE THREAD

**Issue by MoSattler** [privacytools/privacytools.io#1916]
https://f-droid.org/en/packages/ch.protonvpn.android
it's giving a 404

**Comment by ph00lt0** [comment]
Looks like it's removed from F-Droid

**Comment by dngray** [comment]
I think it might be because of https://github.com/ProtonVPN/android-app/issues/1#issuecomment-627314891

It should sort itself out in a while hopefully.

**Comment by dngray** [comment]
This is fixed now that a new build has been uploaded.
