### ISSUE TITLE
❌ Software Removal | DataCell, Orange Website

### ISSUE THREAD

**Issue by niftylettuce** [privacytools/privacytools.io#1919]
## Description

Both DataCell and Orange Website have severe flaws, from SSL issues to mailboxes that do not receive messages since they are not set up.  These should be removed.  Any service provider that has a contact form that doesn't go anywhere can't possibly be trusted.  Furthermore any provider that has emails going out to customers shouldn't have images with missing links, or links to websites that have invalid SSL certificates with different hostnames.  This is INSANE that these are listed here.  Do you just list these providers without even testing them?

<img width="711" alt="Screen Shot 2020-05-14 at 6 16 54 PM" src="https://user-images.githubusercontent.com/523141/81995703-a596fb80-9610-11ea-82e2-6533d0bc9a7a.png">
<img width="1070" alt="Screen Shot 2020-05-14 at 4 53 26 PM" src="https://user-images.githubusercontent.com/523141/81995708-aaf44600-9610-11ea-8779-f3c42113f829.png">
<img width="405" alt="Screen Shot 2020-05-14 at 4 42 35 PM" src="https://user-images.githubusercontent.com/523141/81995713-ad56a000-9610-11ea-8a05-8627d5e5c8da.png">
<img width="686" alt="Screen Shot 2020-05-14 at 4 42 26 PM" src="https://user-images.githubusercontent.com/523141/81995716-afb8fa00-9610-11ea-99ec-88434698b50e.png">

## Why I am making the suggestion

I attempted to purchase dedicated servers from them, and issue after issue arose.

## My connection with the software

I'm a customer attempting to get service.

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by ph00lt0** [comment]
That is odd. Also the fact that they use Gmail is not very promising.

**Comment by FreddyMarsden** [comment]
[OpenBSD Amsterdam](https://openbsd.amsterdam/) could be a good replacement. They got an  [A+ Score on SLLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=openbsd.amsterdam). Might submit a separate issue.

**Comment by niftylettuce** [comment]
@FreddyMarsden I don't think so due to the country's privacy laws and being Member of Nine Eyes and Fourteen Eyes Alliances

**Comment by FreddyMarsden** [comment]
#1365 might also be relevant replacements.

**Comment by blacklight447-ptio** [comment]
I do have to mention that the provider page was added back when privacytools was a lot smaller, we have been planning to redo it with an added criteria list, for now, i think it would be best to remove these till we have the new page set up, @privacytools/editorial

**Comment by shortenjukebox** [comment]
Covered DataCell’s seemingly negligent ownership in #1949. The CEO runs two large-scale ISPs and another hosting provider, and has not expressed much concern for DataCell in the past few years. It did host Wikileaks for some period of time, but that likely ended 4-7 years ago.

**Comment by niftylettuce** [comment]
Thank you @FreddyMarsden and @dngray
