### ISSUE TITLE
📝 Correction | Njalla provider blocks port 25

### ISSUE THREAD

**Issue by niftylettuce** [privacytools/privacytools.io#1920]
## Description

We should note that the provider Njalla blocks port 25 traffic, and has other restrictions.  Official response from them below:

<img width="715" alt="njalla" src="https://user-images.githubusercontent.com/523141/82030063-8a061200-965d-11ea-858f-69278ae1ffd8.png">

## Why I am making the suggestion

Because people should be aware of this.

## My connection with the software

I'm a researcher setting up servers.

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by niftylettuce** [comment]
Related to research with https://github.com/privacytools/privacytools.io/issues/1919

**Comment by blacklight447-ptio** [comment]
good catch, ill try and make a PR for this later.

**Comment by Mikaela** [comment]
I think this is standard behaviour in Nordic countries and may affect other providers too.
