### ISSUE TITLE
🗄️ DNS provider suggestion | LibreDNS

### ISSUE THREAD

**Issue by FreddyMarsden** [privacytools/privacytools.io#1922]
## Basic Information

**Name:** LibreDNS
**Category:** DNS
**Privacy policy:** [LibreOps Privacy Policy](https://libreops.cc/terms.html)
**Protocols:** DoH and DoT
**URL:** [libredns.gr](https://libredns.gr/)
**Server/Location:** ?
**Source:** [GitLab](https://gitlab.com/libreops/libredns/libredns-cfg)
**Type:** [Informal collective](https://libreho.st/)

## Description

**Required features:**

- [x] DNS over HTTPS
- [x] DNS over TLS
- [x] No logs kept.

## Why I am making the suggestion

> The goal is to offer a public encrypted DNS service that people can use to maintain the secrecy of their DNS traffic, but also circumvent censorship.

(Taken from the site)

## My connection with the software

None.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by blacklight447-ptio** [comment]
They are part of the librehosters network and have all income go through Opencollective. Also the fact that the contact information and names of several team members being there, plus supporting both DoT and DoH is encouraging, i vote for adding this provider.

**Comment by nitrohorse** [comment]
Hmm, I agree. No red flags stand out to me; looks like a good option. I can add them in the [cleanup PR](https://github.com/privacytools/privacytools.io/pull/1900).

**Comment by nitrohorse** [comment]
Hmm, are we able to determine if LibreDNS supports QNAME minimisation? :thinking:

> Run `dig +short txt qnamemintest.internet.nl` from the command-line. If you are on Windows 10, run `Resolve-DnsName -Type TXT -Name qnamemintest.internet.nl` from the PowerShell. You should see this display: "HOORAY - QNAME minimisation is enabled on your resolver :)!"
