### ISSUE TITLE
Remove "self-hosted" mention on AnonAddy

### ISSUE THREAD

**Issue by dannymc88** [privacytools/privacytools.io#1925]
## Description

On the https://www.privacytools.io/providers/email/ page, AnonAddy is mentionned as "Can be self-hosted" but when checking their repository, the instructions are not complete.

This is also mentioned in https://github.com/privacytools/privacytools.io/issues/1832#issuecomment-616225134

## Why I am making the suggestion

I've tried to setup my own email alias server and followed AnonAddy self-hosting instructions. I was unpleasantly surprised to notice that the instructions are not complete. The SimpleLogin self-hosting setup seems to work though.

## My connection with the software

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
I'll reach out to them and ask for an update.

**Comment by willbrowningme** [comment]
I've just added the full self-hosting instructions to the repo here - https://github.com/anonaddy/anonaddy/blob/master/SELF-HOSTING.md

If you have any feedback on the instructions please let me know so I can keep improving them.

**Comment by dannymc88** [comment]
@dngray @willbrowningme great, thank you for the detailed instructions!

**Comment by nitrohorse** [comment]
> I've just added the full self-hosting instructions to the repo here - https://github.com/anonaddy/anonaddy/blob/master/SELF-HOSTING.md
> 
> If you have any feedback on the instructions please let me know so I can keep improving them.

Great to see @willbrowningme 👏🏼
