### ISSUE TITLE
🆕 Software Suggestion | IPredator VPN

### ISSUE THREAD

**Issue by FreddyMarsden** [privacytools/privacytools.io#1941]
### Basic Information

**Name:** IPredator
**Category:** VPN
**URL:** [ipredator.se](https://ipredator.se/)

### Description

**Jurisdiction:**
<blockquote>IPredator is incorporated in Cyprus. The service is basically a Swedish broadband prepaid flatrate offered over the Internet. This means that the legal framework mainly consists of the Electronic Communications Act 2003 389.</blockquote>

**Technology:**
- [x] OpenVPN support.
- [x] Client is [open source](https://ipredator.se/netsplice)

**Privacy:**
- [x] Doesn't require personally identifiable information (PII) besides username and password.
- [x] Accepts Bitcoin and Paypal

**Security:**
They don't appear to have been publicly audited.

**Trust:**
- [x] Public-facing leadership or ownership.

**Marketing:**
- [x] No analytics found, complies with DNT?
- [x] No poor claims.

### Why I am making the suggestion

They are made by the same people as Njal.la, a site recommended by privacytools.io

### My connection with the software

I have no connection with the software, however I am enthusiastic about it.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
> They don't appear to have been publicly audited.

That's pretty much a requirement these days. It's the same reason we didn't add AzireVPN.

**Comment by freddy-m** [comment]
[IPredator is now joining Njalla](https://njal.la/blog/ipredator/) - something to keep an eye on.
