### ISSUE TITLE
🆕 Software Suggestion | Opticole

### ISSUE THREAD

**Issue by Onit333** [privacytools/privacytools.io#1942]
## Basic Information

**Name: Opticole**
**Category: Windows Privacy Tool & File Encryption**
**URL: www.riserbo.com/opticole.html**

## Description
Opticole is an easy-to-use Windows privacy toolkit with a simple GUI. I think it's best to compare it to a Swiss army knife, but for privacy. It all runs immediately off of one executable and doesn't need to be installed which I think is pretty cool. Currently I believe the only method of purchasing it is through a credit card, but I contacted the developers who got back and said BTC payments will be available soon. Also, no account is required or anything like that.

## Features
These are the current features I'm aware of:
- [x] File and directory encryption/decryption (includes an option for a custom key)
- [x] Automatic enabling of Windows privacy settings. Original settings can be saved and restored
- [x] Port scanning which guards against malicious payloads
- [x] Computer performance boosting

## Why I am making the suggestion

Windows can be very problematic when it comes to privacy. I love using Windows, but I also know additional privacy apps/software are necessary to protect my data while using it. Opticole is perfect because it's so easy-to-use and non-intrusive. I don't have to worry about any annoying pop-ups or start-up programs. I can just run it whenever I need it.

## My connection with the software

As far as I know, I was one of the first people to purchase Opticole. I'm content with the software, and I want to share it since it's very new and doesn't get a lot of attention.
- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by ph00lt0** [comment]
Website does not have an SSL certificate.

**Comment by danarel** [comment]
Closed source, an invalid Twitter account and their contact is a gmail account.

Nothing about this seems like something we should endorse.

**Comment by ph00lt0** [comment]
Website does not have a SSL-certificate

**Comment by blacklight447-ptio** [comment]
Yeah, this seems a bit shady, also, i wouldn't even know what section this would be added too.
Closing issue (if people disagree, feel free to comment to reopen it for discussion)
