### ISSUE TITLE
❌ Software Removal | Web Hosting: DataCell

### ISSUE THREAD

**Issue by shortenjukebox** [privacytools/privacytools.io#1949]
## Description

DataCell is currently suggested¹ as a web hosting provider, described as a “data center providing secure colocating in Switzerland and Iceland.”

## Why I am making the suggestion

No signs of life from the company, doing little overall to indicate reliability or earn trust from a prospective customer.

The copyright statement on their [website](https://datacell.is/) is out-of-date, with the last blog updates being from 2017. They have a [Twitter](https://twitter.com/datacellcom) account, though there have been no posts relevant to the company since 2015. Meanwhile, their privacy policy has not been updated since 2012. Perhaps more vital, while their [system status](https://datacell.is/support/system-status/) page does not report any incidents, it does not provide any live uptime monitoring to verify that.

No information is readily available on the company’s ownership or stakeholders, except in their very [first blog post](https://datacell.is/news/credit-card-donation-to-wikileaks-is-now-accepted-again) in 2011. CEO Andreas Fink does keep a presence on [Twitter](https://twitter.com/kiwi66), though he has not said [anything](https://twitter.com/search?f=live&q=include%3Anativeretweets+from%3Akiwi66+datacell&src=typed_query) about DataCell since 2018.

Delving deeper, Fink [claims](https://www.fink.org/https://www.fink.org/curiculum-vitae.php) additional CEO roles at [Backbone](https://www.backbone.is/) (Internet backbone service provider), [Cajutel](https://cajutel.io/) (Internet service provider), and [Rackbone](https://rackbone.ch/) (hosting provider). Despite the implied large scale of his four operations, only one mentions having staff other than Fink. As of the past year, according to his Twitter, Fink’s sole focus appears to have been launching Cajutel and raising capital through a cryptocurrency initial coin offering.

Although they [once hosted WikiLeaks](https://wikileaks.org/MasterCard-breaks-ranks-in.html), without experience of using DataCell’s services, there has been little evidence to trust in their reliability. While it has been in business for more then ten years, it is difficult to find evidence that their service is well-maintained by dedicated personnel and prepared to face future technical or legal challenges.

## My connection with the software

None. Saw mention of PrivacyTools’s reputation depending on its recommendations, thought that this one could use further consideration.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

¹ Internet: https://www.privacytools.io/providers/hosting/, Tor: `http://privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion/providers/hosting/`

**Comment by FreddyMarsden** [comment]
#1919

**Comment by shortenjukebox** [comment]
Ah, my apologies. I’ll add some of my comments there.
