### ISSUE TITLE
🆕 Software Suggestion | ImSter

### ISSUE THREAD

**Issue by armytricks** [privacytools/privacytools.io#1958]
## Basic Information

**Name:** ImSter
**Category:** Encryption
**URL:** https://github.com/armytricks/ImSter

## Description
Free and open source multi-platform image steganography software. Encryption is 256-bit AES.

## Why I am making the suggestion
Lot's of software focuses on secure encryption. This one provides both secure encryption and a way to conceal the fact that secret data exists in the first place.

## My connection with the software
I am the author of this software.

-  [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by ph00lt0** [comment]
Not sure how this is of any help to the visitors of PTIO. Seems like a nice script you made but I don't think it qualifies for listing. I have seen many applications accomplishing this, how does yours stand out?

**Comment by armytricks** [comment]
> Not sure how this is of any help to the visitors of PTIO. Seems like a nice script you made but I don't think it qualifies for listing. I have seen many applications accomplishing this, how does yours stand out?

I'm yet to see such an application that uses AES with CBC encryption mode. As a result, I think this stands out by being genuinely more secure than other open source solutions out there. Furthermore, it is fully featured with both a GUI and CLI, and is multi-platform with a single binary making it very accessible and flexible.

**Comment by ph00lt0** [comment]
Pretty sure this one for example uses AES:
https://github.com/guardianproject/PixelKnot

I don't undervalue your project, I just don't think it's that helpful to average visors looking for privacy friendly ways to communicate etc.

**Comment by armytricks** [comment]
> Pretty sure this one for example uses AES:
> https://github.com/guardianproject/PixelKnot
> 
> I don't undervalue your project, I just don't think it's that helpful to average visors looking for privacy friendly ways to communicate etc.

The project you linked is no longer developed. If you look on the Play Store listing it has a 2.6/5 rating because of instability.

I understand what you're saying though. It doesn't have much general applicability, so I'll close this.
