### ISSUE TITLE
📝 Correction | Bitwarden Logo

### ISSUE THREAD

**Issue by Lostname777** [privacytools/privacytools.io#1960]
Bitwarden have updated their logo and darken it, please update it in your website.

Link: https://raw.githubusercontent.com/bitwarden/brand/master/icons/icon.svg

**Comment by FreddyMarsden** [comment]
Submit a PR maybe?

**Comment by Lostname777** [comment]
@FreddyMarsden can you please do it?

**Comment by jackmchou** [comment]
Hello, I'd like to contribute to this issue and have successfully set-up the project on my local machine. I've updated the SVG icon in the assets/img/svg/3rd-party folder. Also ran a live build to check the icon is working as intended  Are there anywhere else the icon needs to be updated? If not, I can submit a PR for this issue. 
![image](https://user-images.githubusercontent.com/56708167/86030118-e98b6780-b9e8-11ea-91fe-0ba3481c3eef.png)

Thank you for your help in advance,
Jack
