### ISSUE TITLE
🌐 Website Issue | Remove erroneous NextCloud link from Signal badge

### ISSUE THREAD

**Issue by misaka00251** [privacytools/privacytools.io#1978]
## Description

When click `Requires phone number`, it will lead to nextcloud's E2EE issue.

Either the link is not correct, or it's wrongfully placed.

## Screenshots

![image](https://user-images.githubusercontent.com/3908746/86513567-bfe59c80-be3d-11ea-8b04-253f79ab1ecc.png)

**Comment by dngray** [comment]
That would be an error... my guess is that *may* have happened when we went over to the new badge system, thanks for spotting that!
