### ISSUE TITLE
❌ Software Removal | Reset the Net - Privacy Pack

### ISSUE THREAD

**Issue by LisaWilbourn** [privacytools/privacytools.io#1983]
## Description
Reset the Net Privacy Pack should be removed from Tools under More Privacy Resources.

## Why I am making the suggestion
On their website they recommend TextSecure and RedPhone which are both apps that predate and were then merged into Signal. As such they have not existed or been maintained in any capacity for 4 years. The fact that such outdated and deprecated software is recommended on their website suggests that the site is not actively being maintained and as such has no value.

## My connection with the software
N/A

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by nitrohorse** [comment]
Yeah, looks abandoned; good call 👍🏼
