### ISSUE TITLE
🆕 Software Suggestion | Session

### ISSUE THREAD

**Issue by 1t3x** [privacytools/privacytools.io#1986]
## Basic Information

**Name:** Session
**Category:** Instant Messaging
**URL:** https://getsession.org/

## Description
Session is a end-to-end encrypted instant messaging app like, like Signal. Session does not need a phone number or an email to make an account so it's more privacy friendly. It actually uses a slightly modified protocol of Signal but it's not centralized.

## Why I am making the suggestion

The main problem I had with Signal is that you needed a phone number to be able to use it, Session on the other hand it does not need anything to make an account.

## My connection with the software

I discovered this app on Twitter, just a user...

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by danarel** [comment]
Duplicate #1678
