### ISSUE TITLE
🗄️ DNS provider suggestion | Foss Daily DNS

### ISSUE THREAD

**Issue by freddy-m** [privacytools/privacytools.io#2002]
## Basic Information

**Name:** Foss Daily DNS
**Category:** DNS
**Privacy policy:** ?
**Protocols:** DoH
**URL:** [fossdaily.xyz](https://fossdaily.xyz/20200710-dns.html)
**Server/Location:** Sydney, Australia
**Source:** ?
**Type:** [Informal collective](https://libreho.st/)

## Description

**Required features:**

- [x] DNS over HTTPS
- [ ] DNS over TLS
- [x] No logs kept.

**Desired features:**

- [x] QNAME minimization

## Why I am making the suggestion

They provide uncensored DNS with DNSSEC validation and built in Adblock using StevenBlack unified hosts file (Adware + Malware).

## My connection with the software

None.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by Mikaela** [comment]
Looks nice with a quick glance, there aren't currently any non-anycasted providers listed in Australia.

**Comment by freddy-m** [comment]
@privacytools/editorial I'd be happy to add this to the site, any objections?

**Comment by freddy-m** [comment]
Would appear as though this services has shut down. Sad, really.
