### ISSUE TITLE
Discussion: Don't use VPN services

### ISSUE THREAD

**Issue by zero77** [privacytools/privacytools.io#2003]
I stumbled across the following post "Don't use VPN services" this will not be applicable for everyone but there are still some valid points made.

Should any of this be added, what are people's thoughts.

https://gist.github.com/joepie91/5a9909939e6ce7d09e29

**Comment by FreddyMarsden** [comment]
This is already listed under the VPN section and has been referenced many times on the [sub-reddit](https://www.reddit.com/r/privacytoolsIO/). Also, this isn't the write place for discussion; it would probably be bested to close this issue and try the [forum](https://forum.privacytools.io/) instead.
