### ISSUE TITLE
🆕 Software Suggestion | VPN Service - OVPN

### ISSUE THREAD

**Issue by udf2457** [privacytools/privacytools.io#2031]
## Basic Information

OVPN
VPN
https://www.ovpn.com/en

## Description

- No log service
- Extensive client support: Wireguard, OpenVPN and own client
- Track record of not releasing data to authorities (because they have none, no logging)

**Comment by dngray** [comment]
I don't believe they've undergone any external auditing.. which is now necessary.

**Comment by udf2457** [comment]
@dngray They are however currently subject to quite an aggressive lawsuit where the claimant has hired a pentester to prove they have something to hide (https://torrentfreak.com/anti-piracy-outfit-hires-vpn-expert-to-help-track-down-the-pirate-bay-200821/).  

I would suggest that if the pentest company comes up with nothing that would effectively be an external audit !

**Comment by dngray** [comment]
> I would suggest that if the pentest company comes up with nothing that would effectively be an external audit !

It most certainly isn't.

External audits methodically test each part of the network. Granted access at certain levels to simulate what would happen if an adversary attained that access.

> The fact OVPN are quite happy to defend this case rather than cave in shows a lot for how confident they are in the security.

People argue about things all the time in court, when they are wrong. This isn't an indicator of anything.

**Comment by udf2457** [comment]
Where's the ProtoVPN audit then @dngray !

**Comment by dngray** [comment]
> Where's the ProtoVPN audit then @dngray !

- https://protonvpn.com/blog/open-source/

**Comment by dngray** [comment]
Additionally they seem to advertise and advise customers to use [closed source software](https://www.sparklabs.com/viscosity/).

**Comment by freddy-m** [comment]
Also, @udf2457 I've reformatted your issue. In future please use the templates provided, we have them for a reason.
