### ISSUE TITLE
🆕 Software Suggestion | Standard Notes (note taking / todo list software)

### ISSUE THREAD

**Issue by udf2457** [privacytools/privacytools.io#2033]
## Basic Information

Standard Notes
Notes / To-Do list
https://standardnotes.org/

## Description

Encrypted note/to-do list software.  Good synchronisation feature.  Cross-platform.

**Comment by freddy-m** [comment]
They are [already listed](https://www.privacytools.io/software/notebooks/). Please check the site before opening issues :+1:
