### ISSUE TITLE
📝 Correction | Add Whonix's hidden service address to the page

### ISSUE THREAD

**Issue by subsys-R9boq8** [privacytools/privacytools.io#2034]
## Description

When I uses Tor browser to access Whonix wiki today, a pop up of tor browser jumped out and inform me that Whonix website can be reached via. hidden service address. Thought it might be great to add a tor hidden service link under the description of Whonix. Here's the address:
http://www.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/

## Why I am making the suggestion

Just adding information to the Whonix section

## My connection with the software

No connection.

- [ ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
Do you have a link on the Whonix site where this onion site is linked?

**Comment by subsys-R9boq8** [comment]
> 
> 
> Do you have a link on the Whonix site where this onion site is linked?

I was notified to jump to this onion link by the tor browser.
It's also written on the whonix wiki, too.
Forcing .onion on Whonix.org
http://www.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/wiki/Forcing_.onion_on_Whonix.org

**Comment by freddy-m** [comment]
Ahh nice, well I'll add it soon!
