### ISSUE TITLE
🗄️ DNS provider suggestion | AmnDNS

### ISSUE THREAD

**Issue by SnwMds** [privacytools/privacytools.io#2035]
## Basic Information

**Name:** AmnDNS
**Category:** DNS
**Privacy policy:** https://github.com/AmanoTeam/AmnDNS#privacy
**Protocols:** DoH and DoT
**URL:** https://amanoteam.com/
**Server/Location:** Canada
**Hosting Provider** OVH
**Source:** [GitHub]( https://github.com/AmanoTeam/AmnDNS)
**Type:** Hobby Project

## Description

AmnDNS is a DNS service with a zero-logging policy. It filters content such as ads, analytics, malware, social media and pornography.

**Required features:**

- [x] DNS over HTTPS
- [x] DNS over TLS
- [x] No logs kept.

**Desired features:**

- [x] QNAME minimization

## Why I am making the suggestion

No reason in particular. I just want to share this service with others.

## My connection with the software

I am one of the authors of this project.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
I've updated your post with information I found from your GitHub and the website you linked. Thus far it looks good to me.
As a side note @privacytools/editorial should we make this a new issue format?

**Comment by SnwMds** [comment]
Thanks. I edited the issue according to the new format.

It's a hobby project and supports QNAME minimization.

**Comment by freddy-m** [comment]
Ahh, thanks for updating. Looks pretty good to me, I'll ask the other team members!

**Comment by SnwMds** [comment]
We have decided to shutdown this service. Thank you for your consideration in adding it to PrivacyTools.
