### ISSUE TITLE
📝 Correction | matrix and fediverse are both federated but they are two separate things

### ISSUE THREAD

**Issue by strypey** [privacytools/privacytools.io#2036]
## Description

On the chat page here:
https://www.privacytools.io/services/chat/

It uses the phrase "Matrix fediverse". I suggest removing "fediverse" from this page completely.

## Why I am making the suggestion

"The fediverse" is the informal name for the federated network of social media apps using ActivityPub (mainly, along with a few other protocol standards like Diaspora, OStatus, and Zot). AFAIK none of these apps connect with the matrix network is any way. Federated networks already cause a lot of confusion for users, especially about which software and services can and can't connect with which other ones. Using the phrase "fediverse" to describe the matrix network can only increase this confusion.

## My connection with the software

I have been doing research for fediverse.party, tracking the evolution of the fediverse and the software involved. See:
https://git.feneas.org/feneas/fediverse/-/wikis/

**Comment by dngray** [comment]
I agree, I'm not entirely sure who added that.
