### ISSUE TITLE
🆕 Software Suggestion | ZeroTier

### ISSUE THREAD

**Issue by unquietwiki** [privacytools/privacytools.io#2038]
## Basic Information

**Name:** ZeroTier
**Category:** Communication
**URL:** https://www.zerotier.com/

## Description

Mesh-based, encrypted Ethernet tunneling; sort of a mix of what tinc and OpenVPN do. Dual-licensed (BSL 1.1)

## Why I am making the suggestion

1. I've been using the software since 2018; deployed it for at least two places of work, and recommended it on Reddit and other places.
2. Ended up joining them a month ago to help with community & code issues.

## My connection with the software

Community Support Manager as of August, 2020

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
Google Analytics present on the homepage, and I see no to list it.
