### ISSUE TITLE
 📝 Correction | Canadian Key Disclosure status 

### ISSUE THREAD

**Issue by markjr** [privacytools/privacytools.io#2039]
## Description

Canada is listed under countries where individuals are subject to key disclosure laws, yet the link to the Wikipedia citation actually reads as the opposite - that attempts to compel individuals to turn over keys have failed in court and that the Canadian Charter of Rights and Freedoms enshrines the right to protect against self-incrimination.

## Why I am making the suggestion

I don't know what the legal status actually is in Canada, but the citation provided in the list actually says the opposite of what Canada's listing in that column suggests.

## My connection with the software

None

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
I've update your issue, please use the templates provided in future. This is definately something to look into, so thanks for opening the issue.

**Comment by markjr** [comment]
Ok thanks - sorry will do in the future.

**Comment by dngray** [comment]
Yes, we need to put a PR in for this. I had forgotten about it https://github.com/privacytools/privacytools.io/issues/1167#issuecomment-604583930
