### ISSUE TITLE
❌ Software Removal | Keybase

### ISSUE THREAD

**Issue by ghost** [privacytools/privacytools.io#2046]
## Description
Keybase does not distribute apk files.
The developer ignores the Issue and refuses to distribute it.
Depends on Google Play.

## Why I am making the suggestion
Should be removed.

## My connection with the software
I have nothing to do with software authors.

- [✔] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by Mikaela** [comment]
Where exactly this ghost sees Keybase listed, I am curious.

**Comment by freddy-m** [comment]
@Mikaela it isn't listed, and was removed in [this PR](https://github.com/privacytools/privacytools.io/pull/1951).
