### ISSUE TITLE
🆕 Software Suggestion | eBlocker

### ISSUE THREAD

**Issue by ph00lt0** [privacytools/privacytools.io#2049]
## Basic Information

**Name:** eBlockerOS
**Category:** 
**URL:** https://eblocker.org

## Description
Software similar to Pihole but a little bit more advanced. They automatically replace all user agents and reroute the traffic over a VPN or tor. 

## Why I am making the suggestion
I think a big advantage could be that they could be more accessible to the masses where Pihole might be too complicated for tech-savvy people.

I have not tried out the software yet, but I think it's worth to have a look at this together with the community as the idea is very promising.

## My connection with the software

No connections

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

Ps the website is down, so I could not find the right category.

**Comment by ph00lt0** [comment]
Few remarks I have so far
- On the English version of the website it states that the services is 21% funded while on the German version is says 73%
- The video on the website claims that devices connect to this devices instead of the router but technically this is incorrect.

**Comment by dngray** [comment]
> Software similar to Pihole but a little bit more advanced. They automatically replace all user agents and reroute the traffic over a VPN or tor.

This is likely to cause a very unique fingerprint. Spoofing user agents is pointless because it can often be circumvented anyway through various JS APIs. There is a good reason that the arkenfox project doesn't recommend it: https://github.com/arkenfox/user.js/wiki/4.1-Extensions#small_orange_diamond-%EF%B8%8F-anti-fingerprinting-extensions-fk-no
