### ISSUE TITLE
🆕 Software Suggestion | Systemd-resolved

### ISSUE THREAD

**Issue by quantmint** [privacytools/privacytools.io#2050]
## Basic Information

**Name:**
systemd-resolved
**Category:**
Encrypted DNS Client
**URL:**
https://www.freedesktop.org/wiki/Software/systemd/resolved/
## Description
Systemd-resolved is fully featured DNS resolver implementation, it supports both dns over tls and DNSSEC.

## Why I am making the suggestion
It's a very good software and it's preinstalled on almost every linux machine.
## My connection with the software
I use it every day.

**Comment by Mikaela** [comment]
Duplicate of https://github.com/privacytools/privacytools.io/issues/1448, but it doesn't ever seem to have made its way onto the DNS page.

Systemd-resolved supporting DNS-over-HTTPS in the future isn't entirely closed out either, https://github.com/systemd/systemd/issues/8639.

**Comment by dngray** [comment]
I think we decided to close this, because it's heavily integrated with systemd support. Your distribution either has support or doesn't.

**Comment by Mikaela** [comment]
Doesn't that also apply to Android 9+?
