### ISSUE TITLE
📝 Correction | ghacks user.js is no more...

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [privacytools/privacytools.io#2051]
## Description

please refer to it as the `arkenfox user.js` - at https://github.com/arkenfox/user.js

If you want, since I don't have a reddit account and can't even be assed grabbing a temp one, a FYI message on `r/rpivacytoolsio` would be welcome

reason for change: the repo has nothing to do with `ghacks.net`
reason for new name: something unique, memorable. Everything to do with fox + privacy/config/harden/whatever all seemed too generic .. and in the end, it was agreed that arkenfox was it

discussion is here: https://github.com/arkenfox/user.js/issues/1009

> > The Arkenstone was a gem, **the object most prized by Thorin Oakenshield of all the treasures** of the Lonely Mountain. **Such did he consider its value** that he was willing to trade 1/14th of all the gold and silver of Smaug's hoard for it.

Obviously no-one will "get" the hobbity "connection" get unless they know my history with the whole thing

@jonaharagon @blacklight447-ptio @Mikaela @who-ever-is-in-charge-and-looks-important

**Comment by Mikaela** [comment]
Hi, I am not actually much involved with PrivacyTools nowadays, but as I am having a focusing problem I opened #2052 and [a forum thread](https://forum.privacytools.io/t/ghacks-user-js-is-now-arkenfox-user-js/4329?u=mikaela). On Reddit you will have to ask someone else.
