### ISSUE TITLE
📝 Correction | Nextcloud's end to end encryption is now production ready.

### ISSUE THREAD

**Issue by epicgoldenlife** [privacytools/privacytools.io#2054]
## Description
On the privacytools.io website next to Nextcloud (in the self-hosted cloud server section), there is a warning saying that nextcloud's end to end encryption is still in an "alpha state" (hover over the Experimental E2EE flag). However, in a recent announcement by nextcloud, they said that end to end encryption is now production ready.

https://nextcloud.com/blog/production-ready-end-to-end-encryption-and-new-user-interface-arrive-with-nextcloud-desktop-client-3-0/

## Why I am making the suggestion

I am making this suggestion as an update to status of Nextcloud on the privacytools.io website. 

## My connection with the software

I am just a user, not affiliated with the company in any way.

- [X ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by AlekseiMarinichenko** [comment]
> they said that end to end encryption is now production ready.

By they words, yes. But basically, if you will look at they issue tracer and at the forum, you will find a lot of bug and unsolved issues. 

Well, technically, we need to mark it as "production ready". But everyone must think twice before using it. Of course, if you do not want to spend the rest of you time recovering your files and fixing bugs,

**Comment by lynn-stephenson** [comment]
I will take a look at the E2EE module soon; see what known issues are open/not-resolved, and look at their implementations on clients.

**Comment by epicgoldenlife** [comment]
That's not the point. They announced that it is production ready, so the tag that says that e2ee is still in "alpha" should be changed. Since they announced it was production ready, it should not be called "alpha" software.
