### ISSUE TITLE
📝 Correction | iOS 14 (& macOS Big Sur?) have native support for encrypted DNS (DoT (strict?), DoH)

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#2059]
## Description

https://www.privacytools.io/providers/dns/#dns-ios-clients only lists DNSCloak, while iOS 14 supports encrypted DNS through installing profiles (or apps that install profiles).

## Why I am making the suggestion

I am iOS user and enthustiastic about encrypted DNS [and have been following the iOS situation at the forum](https://forum.privacytools.io/t/apple-adds-support-for-encrypted-dns-doh-and-dot-zdnet/3792?u=mikaela) where I am thankful for Nitrohorse on correcting me that apps aren't necessary.

* [Adguard blog post on encrypted DNS for iOS including their signed profiles amongside screenshotted install instructions](https://adguard.com/en/blog/encrypted-dns-ios-14.html). I think this may also be helpful for non-iOS team members to read to get a picture on how it works.
* [Reddit guide on making profiles by yourself](https://www.reddit.com/r/MacOSBeta/comments/i21e59/how_to_set_up_cloudflare_dns_over_tls_secure_dns/)
* [Couple of profiles made by a Reddit user](https://mc.ipv6.com.es/dns/index.htm) (I think this should have a warning to check the profile before installing to see that the addresses look OK).
* NextDNS 2.0 <s>(in Testflight at time of writing)</s> app includes a profile.
* [Some profiles by Nitrohorse on mobileconfigs.netlify.app](https://mobileconfigs.netlify.app/) / [GitLab source](https://gitlab.com/nitrohorse/ios14-encrypted-dns-mobileconfigs)

## My connection with the software

I am one of the original authors of the PrivacyTools DNS page, with the software I have no further connection than being an user of NextDNS (due to them being the first adaptor of the native iOS 14 support) and I have joined Adguard's *Telegram group chat* out of curiosity.

Connection update 2020-10-18: I have opened [a merge request towards Nitrohorse's mobileconfigs.netlify.app](https://gitlab.com/nitrohorse/ios14-encrypted-dns-mobileconfigs/-/merge_requests/1) and he is also PrivacyTools Team Member Emeritus.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by blacklight447-ptio** [comment]
Thanks mikeala, would you be willing to make a Pr for this?

**Comment by Mikaela** [comment]
I fear that I need to handle some personal issues first before I am able to look into this, so I cannot give any timetable promises and it may happen faster if someone else picks it up.

**Comment by Mikaela** [comment]
> For some convenience/reference, I started creating DoH profiles for other providers.
> https://mobileconfigs.netlify.app/
> https://gitlab.com/nitrohorse/ios14-encrypted-dns-mobileconfigs

says @nitrohorse [on the forum](https://forum.privacytools.io/t/apple-adds-support-for-encrypted-dns-doh-and-dot-zdnet/3792/14?u=mikaela) adding 5th point.
