### ISSUE TITLE
 ❌ Software Removal | Remove F-Droid Fennec Link

### ISSUE THREAD

**Issue by MetalNeo** [privacytools/privacytools.io#2066]
## Description
Fennec is now considered EOL and has been superseded by Fenix (https://www.mozilla.org/en-US/firefox/android/68.11.0/releasenotes/).

## Why I am making the suggestion

I don't believe that we should be recommending browsers that are no longer being actively developed, mainly for security reasons.

## My connection with the software

Regular user of Fennec before the official release of Fenix

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by JJohnGreenSr** [comment]
Shouldn't this be tagged as [❌ software removal](https://github.com/privacytools/privacytools.io/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%9D%8C+software+removal%22)

**Comment by dngray** [comment]
I looked on F-Droid's issue tracker for a beta of Fenix, but there doesn't seem to be one. Only thing I found was this: https://gitlab.com/fdroid/fdroiddata/-/issues/2161

**Comment by dngray** [comment]
This thread someone made me aware of https://forum.f-droid.org/t/welcome-a-new-fennec-f-droid/11113

**Comment by dngray** [comment]
This has now been updated.
