### ISSUE TITLE
❌ Software Removal | Enigmail

### ISSUE THREAD

**Issue by bwmravec** [privacytools/privacytools.io#2072]
## Description

Enigmail is now considered EOL for Thunderbird and has been superseded by built-in OpenPGP solution by Thunderbird

(https://www.enigmail.net/index.php/en/home/news/70-2019-10-08-future-openpgp-support-in-thunderbird).
It will keep working for paid email client Postbox and some old fork of Thunderbird (https://binaryoutcast.com/projects/interlink/) with not clear future or active development.

## Why I am making the suggestion

I don't believe that we should be recommending add-ons that are no longer being actively developed, mainly for security reasons.

## My connection with the software

Regular user of Enigmail

**Comment by ph00lt0** [comment]
Enigmail is still a used in other email clients as plugin as well.

**Comment by dngray** [comment]
We're already aware of this as a part of https://github.com/privacytools/privacytools.io/issues/1707#issuecomment-593450587
