### ISSUE TITLE
✨ Feature Suggestion | Changelog to the website

### ISSUE THREAD

**Issue by 3k2** [privacytools/privacytools.io#2079]
It's very hard to find information why certain service/browser addon etc has been removed or added. Like for example couple of months ago I visited Privacytools.io to check if there has been any new browser recommendations. Well to my surprise Cookie Auto Delete was removed I tried to search the website for some changelog or blog post why this was the case but couldn't find any answer why all sudden it wasn't recommended to use anymore. But it would appear for Android it is recommended. 

That's why I'd suggest adding some sort of changelog or blog post where people can easily find information why certain changes has been made.

**Comment by LongJohn-Silver** [comment]
I've been thinking about this, too, it would be a great idea, and the only thing you would have to do is describe the change the link to their respective Github issues.

**Comment by nitrohorse** [comment]
One option that comes to mind that works across all GitHub repos is subscribing to the commit (change) history via RSS: https://github.com/privacytools/privacytools.io/commits/master

**Comment by nitrohorse** [comment]
One option that comes to mind that works across all GitHub repos is subscribing to the commit (change) history via RSS: https://github.com/privacytools/privacytools.io/commits/master.atom (add “.atom” to the URL)

**Comment by blacklight447-ptio** [comment]
@freddy-m Was interested in writing a  "this month in privacytools" news letter, maybe this could work out?

**Comment by LongJohn-Silver** [comment]
@blacklight447-ptio I think although that's better than nothing, it's not something so good since it's not so organised as a changelog, and also has a lot more of information than what you might need. Also with a changelog you can browse what was removed five years ago and why in some sort of list, whereas with blog posts you would have to dig up a lot of posts before reaching what you're interested in.

**Comment by blacklight447-ptio** [comment]
Tbh, for something that goes back five years, we already have our commit log, so people who really want to dig in can always find it there.

**Comment by BurungHantu1605** [comment]
Good idea. It could be done very simple with a text based changelog, manually. We explain in one short sentence what has been changed / removed / added and link to the github discussion. It might be even worth it to hide this behind a "notification bell" in the header menu with the latest 10 items and with a "more..." link, the menu unfolds when you click on it. It's nowhere near a complete changelog, only items should be added that affect content (added / removed / edited)

**Comment by lynn-stephenson** [comment]
A good idea might be to "release" PT with semantic versioning.

Declaring any additions, removals, changes, etc.

**Comment by LongJohn-Silver** [comment]
> Tbh, for something that goes back five years, we already have our commit log, so people who really want to dig in can always find it there.

It was just an example, because if you create the changelog, after 5 years of it being active, you can still browse it in a comfortable manner.

> A good idea might be to "release" PT with semantic versioning.
> 
> Declaring any additions, removals, changes, etc.

I would still prefer the changelog, but that's me.

**Comment by wylel** [comment]
Issue #2104 talks about this as well.

**Comment by lynn-stephenson** [comment]
This issue is being closed (more like moved), as #2104 is more generic. Discussion should continue there.
