### ISSUE TITLE
✨ Feature Suggestion | disable sensor in firefox

### ISSUE THREAD

**Issue by rhjdvsgsgks** [privacytools/privacytools.io#2084]
search device.sensors in about:config , turn all "enable" flags to false, can be used to prevent websites from use accelerometer to record audio indirectly

**Comment by blacklight447-ptio** [comment]
Seems like a reasonable addition, @Thorin-Oakenpants what do you think?

**Comment by Thorin-Oakenpants** [comment]
ignore it, close with prejudice

**Comment by blacklight447-ptio** [comment]
Any elaboration?

**Comment by rhjdvsgsgks** [comment]
@Thorin-Oakenpants 
sorry, i'm not a native speaker of english, and i can't understand what means of "prejudice" here, could you please explain it ?
if you think i have some prejudice in what i said before, i apologize to you here

**Comment by LongJohn-Silver** [comment]
It seems like a good addition, if it does what you say it does, for laptop users or people who have a microphone plugged in all day on their desktop machines.

**Comment by rhjdvsgsgks** [comment]
@LongJohn-Silver 
I think you may misunderstand, this flag is more target to mobile platform which have accelerometer. if you want to prevent website access microphone, you can deny "microphone" permission

**Comment by Thorin-Oakenpants** [comment]
> Any elaboration?

- where are the sources, papers on this? (not doubting op, and I already know sensors have other FP issues: but everything needs sources in order to evaluate)
- what is the *actual* threat? e.g. I know sensors provide a high precision timestamp and the application of that means different things. What is the end threat here of this "audio recording" - what is the it recording. Audio may just a simple way to hash the combined sensor data and is not required .. this is why we need sources
- what is the proper solution? i.e not some blanket "set everything to false"
- what do Mozilla and RFP and TB say
- who is this solution targeted at? - Fenix users with about:config access, right? That's very niche
- who is PTIOs audience?

**Comment by Thorin-Oakenpants** [comment]
I commented at [tor project](https://gitlab.torproject.org/tpo/applications/fenix/-/issues/40074#note_2711271) - typically this is something that should get handled upstream under RFP: most likely under [bugzilla 1562290](https://bugzilla.mozilla.org/show_bug.cgi?id=1562290)

**Comment by rhjdvsgsgks** [comment]
[here](https://www.ndss-symposium.org/ndss-paper/learning-based-practical-smartphone-eavesdropping-with-built-in-accelerometer/) is the source and paper (maybe)

**Comment by Thorin-Oakenpants** [comment]
thanks - i'll add that to the tor ticket notes

**Comment by Thorin-Oakenpants** [comment]
IMO, you can close this. My source tells me it looks like this attack is impractical from a webpage. Also note the default settings: ambientLight and proximity aren't exposed. Orientation doesn't matter (except allow you to change orientation: big deal) and the master switch .enabled is immaterial, as is the .test.events

Which only leaves motion. I didn't read the paper in detail. But this is a very niche attack, if even at all possible/practical within Fenix

device.sensors.*
```
- ambientLight.enabled ; false // devicelight (false since FF62)
- enabled              ; true
- motion.enabled       ; true
- orientation.enabled  ; true
- proximity.enabled    ; false // userproximity and deviceproximity (false since FF62)
- test.events          ; false // FF70+
```

**Comment by Thorin-Oakenpants** [comment]
I knew I was missing something: it's already covered by RFP: [1369319](https://bugzilla.mozilla.org/show_bug.cgi?id=1369319)
