### ISSUE TITLE
🆕 Software Suggestion | Userbase

### ISSUE THREAD

**Issue by j-berman** [privacytools/privacytools.io#2107]
## Basic Information

**Name:** Userbase
**Category:** Service Provider - Cloud Storage
**URL:** https://userbase.com

## Description

Userbase is a tool developers use to build private web applications. Userbase offers built-in user accounts and authentication, an end-to-end encrypted zero-management database and file storage solution, and a way to accept subscription payments. All Userbase features are accessible through a very simple open source Javascript SDK, directly from the browser.

Both the Userbase client and server are [open-source](https://github.com/smallbets/userbase), and have undergone an independent security review ([link](https://userbase.com/announcements/#1-security-review)).

From the review:

>[Cossack Labs](https://www.cossacklabs.com/) found that Userbase prevents an adversary with privileged access to the Userbase server from accessing protected user data under the chosen set of assumptions and constraints.

## Why I am making the suggestion

It's a useful tool for web developers seeking to create privacy-focused applications. They don't need to roll their own, Userbase exposes a super simple API that ensures their users' data is kept private for them.

While true that whoever hosts the web app using Userbase can in theory modify the web app to get user data, Userbase is still a step forward for privacy for the following reasons:

- It protects data at rest on the server-side. Inactive users wouldn't be affected assuming the initial code they loaded when they used the app was not modified.
- Malicious intent is needed to access protected user data, which is a much higher bar to reach compared to the norm of sending the server all your data in plaintext by default and trusting the server to handle the data properly.
- Developers can make the build of their web app available for download and accessible locally.
- The client SDK is tested working in [electron](https://www.electronjs.org/), which means it can be used to build desktop applications.

## My connection with the software

I work at Userbase and helped write the code.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by lynn-stephenson** [comment]
This is a tool for developers. We do not have a section dedicated for developers. Our target demographic is average users, hence it does not make sense for us to recommend it.

**Comment by j-berman** [comment]
Ah, got it. Any thoughts on adding a section dedicated for developers in the future :D

**Comment by lynn-stephenson** [comment]
No advice as of now, it is a complicated subject. Nice project, though.
