### ISSUE TITLE
✨ Feature Suggestion | Do and don't when traveling

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [privacytools/privacytools.io#2118]
## Description
Lets say u go on a holiday by plane. How would u remain the security/privacy of u and ur devices. 
Can the airport snoop on your devices? If they are allowed to how do u prevent this. Is there even a way to prevent this?
I even heard that encrypting ur laptop hard drive is a huge red flag at airport security. 
What precautions are there to take before going to the airport?
When at the airport what are things u should and things u shouldn't do (maybe in certain situations idk)
These could be questions/worries people could have.
It would be nice if this would be mentioned in maybe the wiki pages.

**Comment by lynn-stephenson** [comment]
I am closing this issue until someone dedicates time to investigating this. This is extremely in-depth, and would require a lot of research. @efb4f5ff-1298-471a-8973-3d47447115dc Consider bringing research to the table, find case studies, conduct your own tests, etc.
