### ISSUE TITLE
✨ Feature Suggestion | Do and don't when shopping online

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [privacytools/privacytools.io#2119]
## Description
Questions on the forums that are asked very often :

How do i make purchases online while keeping my anonymity? 

Or is there any service or privacytool that helps me keeping my anonymity? 

What things u certainly should not do when shopping online?

Maybe this can be somehow implemented in the wiki pages

**Comment by lynn-stephenson** [comment]
It is not possible to "anonymously" do online shopping, at least with the internet's current state.

There can be very basic measures to preventing account theft, and such. But with the majority of purchases being done on invasive services that legally require your personal information, is not very effective.

Encouraging some privacy measures may encourage users to break laws. Such as not providing your legal name for some services that explicity require it.

**Comment by freddy-m** [comment]
This could be done as a blog post, though I feel that Lynn has done it justice here.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@freddy-m this link does not work.

**Comment by rusty-snake** [comment]
https://www.startpage.com/privacy-please/privacy-advocate-articles/5-online-shopping-tips-to-keep-your-financial-data-secure
