### ISSUE TITLE
❌ Software Removal | mailbox.org

### ISSUE THREAD

**Issue by KurnTu59** [privacytools/privacytools.io#2121]
## Description
I suggest removing mailbox.org.

## Why I am making the suggestion
mailbox.org is not properly configured with DANE.
https://ssl-tools.net/mailservers/mailbox.org
https://ssl-tools.net/webservers/mailbox.org
https://ssl-tools.net/webservers/login.mailbox.org

## My connection with the software
I have nothing to do with the operator of mailbox.org.

- [✅] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
> mailbox.org is not properly configured with DANE.
> https://ssl-tools.net/mailservers/mailbox.org

The error is a false positive "unexpected EOF" which might indicate the testing tool was throttled and didn't complete the test.

https://www.hardenize.com/report/mailbox.org/1605030434#email_dane indicates no issues.

> https://ssl-tools.net/webservers/mailbox.org
> https://ssl-tools.net/webservers/login.mailbox.org

These two are HTTP related servers, DANE verification happens in practically no browser, and we don't require it to.

Closing, everything is working.
