### ISSUE TITLE
🆕 Software Suggestion | New Firefox 83 HTTPS-Only Mode 

### ISSUE THREAD

**Issue by xetxezarreta** [privacytools/privacytools.io#2131]
## Basic Information

**Name:** Firefox 83 HTTPS-Only Mode 
**Category:** HTTPS
**URL:** https://blog.mozilla.org/security/2020/11/17/firefox-83-introduces-https-only-mode/

## Description
Firefox 83 has released a new HTTPS-only feature. My suggestion is using this option instead of the HTTPS-Everywhere addon.

## Why I am making the suggestion

To avoid using an extra addon when a similar option is available natively.

## My connection with the software
Enthustiastic.

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
Duplicate of #1292.
