### ISSUE TITLE
❌ Software Removal | Mailpile

### ISSUE THREAD

**Issue by KurnTu59** [privacytools/privacytools.io#2133]
## Description
I suggest the removal of Mailpail.

## Why I am making the suggestion
Mailpail depends on Python2.
The development of Python2 was finished in April 2020.

## My connection with the software
I am not related to the developer of this software.
- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
#1990

**Comment by dngray** [comment]
> Mailpail depends on Python2.

It looks like it will be Python3 support will be soon https://github.com/mailpile/Mailpile/issues/160#issuecomment-726272328

Only thing they're waiting on is [pydns](https://pypi.org/project/pydns/). 

[py3dns looks unmaintained](https://sourceforge.net/projects/pydns/files/py3dns/) so they're going to have to find an alternative I think.
