### ISSUE TITLE
🌐 Website Issue | Latest commits not appearing

### ISSUE THREAD

**Issue by samuel-lucas6** [privacytools/privacytools.io#2135]
## Description
The last 5 commits (#2115, #2129, #2124, #2114, #2108) haven't appeared on the website yet. There appears to be some serious delay - the oldest was 25 days ago.

**Comment by dngray** [comment]
Hmm this is an issue we'll have to look into. Not sure why this happens sometimes.

**Comment by dngray** [comment]
Seems to have happened to the new email client page https://github.com/privacytools/privacytools.io/commit/5142ef18ab4d762b3570c6552a780685a1c20cb6

**Comment by dngray** [comment]
Fixed
