### ISSUE TITLE
❌ Software Removal | gpg4usb

### ISSUE THREAD

**Issue by minoplhy** [privacytools/privacytools.io#2136]
## Description
I suggest the removal of gpg4usb

## Why I am making the suggestion
* gpg4usb has not been updated since 2016-01-05
* From the gpg4usb official repository README.md says : 
>NOTE
>This software is not maintained anymore. please feel free to fork. The appropriate build environment is available at  https://github.com/gpg4usb/gpg4usb-docker

* This project has been archived since 2020-02-21

## My connection with the software
I'm not related to the developer of this software.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by samuel-lucas6** [comment]
This sounds like a good idea. Most of the issues open on [GitHub](https://github.com/gpg4usb/gpg4usb/issues) haven't been closed, which suggests it's a buggy program that's potentially unsafe to use.

**Comment by freddy-m** [comment]
I'm in favour of this - I'll be submitting a PR soon.

**Comment by samuel-lucas6** [comment]
> I'm in favour of this - I'll be submitting a PR soon.

I'm afraid I beat you to it :) Thought it was a good first PR since it's a simple commit.

**Comment by dngray** [comment]
I should get a change to review this later today, likely though we will just merge https://github.com/privacytools/privacytools.io/pull/1990
