### ISSUE TITLE
❌ Software Removal | Disroot

### ISSUE THREAD

**Issue by KurnTu59** [privacytools/privacytools.io#2138]
## Description
Suggest removal of the Disroot.

## Why I am making the suggestion
TLS1.3 is disabled on disroot.org:443 and disroot:org:465.
In disroot.org:465, TLS1.0 is enabled.

This is not desirable for security.

## My connection with the software
Disroot user.

- [✅] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
I think it would be a smarter idea to contact the sysadmins, inform them of this and help to make their services (which is really odd and rare to find a project that is able to maintain so many of them) better than delisting them... just saying.

**Comment by dngray** [comment]
> TLS1.3 is disabled on disroot.org:443 and disroot:org:465.

It supports TLS 1.2 with correct cipher suite preferences. They will likely allow TLS 1.3 soon. Most modern browsers won't in fact use anything lower than TLS 1.2.

> In disroot.org:465, TLS1.0 is enabled.

It is, but a cipher suite is set. It will only be used by incoming servers that don't support anything newer.

In the *Minimum* criteria says:

> A server suite preference of TLS 1.2 or later and a plan for [Deprecating TLSv1.0 and TLSv1.1](https://datatracker.ietf.org/doc/draft-ietf-tls-oldversions-deprecate/).

Though I did notice a few things with this detailed report. I've also emailed them it. 

```
./testssl.sh -t smtps disroot.org:587 |
    aha --black -t "disroot.org (SMTP)"> disroot.org.html
```

[disroot.org_20201126.html.gz](https://github.com/privacytools/privacytools.io/files/5598158/disroot.org_20201126.html.gz)
