### ISSUE TITLE
📝 Correction | Invidious wording is incorrect - you are still communicating with Google

### ISSUE THREAD

**Issue by bkil** [privacytools/privacytools.io#2144]
## Description

If you open up a video from an Invidious instance and inspect the networking tab of the developer toolbar, you will clearly find that your video chunks are coming from `googlevideo.com`. Google not only sees your IP, but they know what you are watching, your connection speed, which parts you find interesting (seek/play/pause), whether you need to speed up or down for comprehension and may fingerprint you based on headers as well. I haven't checked what else they can do.

## Why I am making the suggestion

The existing wording is misleading: `you can keep watching videos without sharing your IP`.

## My connection with the software

No connection.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by bkil** [comment]
Oh, I found a hint in the documentation, this seems to be an optional feature:
- https://github.com/iv-org/documentation/blob/master/Always-use-%22local%22-to-proxy-video-through-the-server-without-creating-an-account.md

As this was not obvious, I think it would be beneficial to mention this.

**Comment by Gusted** [comment]
Hi @bkil!

Please check my comment over at #2182 I think you might want to add some information to it.

Regards,
Gusted

**Comment by bkil** [comment]
Thank you, I think the warning is adequate from my perspective.
