### ISSUE TITLE
📝 Correction | Incorrect Open Collective sponsor link

### ISSUE THREAD

**Issue by implete** [privacytools/privacytools.io#2145]
## Description
In the "Sponsor the page" tab on the right, the current link is https://opencollective.com/privacytoolsio, when it should be https://opencollective.com/privacytools

## Why I am making the suggestion
I tried to checkout the open collective privacytools sponsor page.

**Comment by dngray** [comment]
I noticed this is also incorrect on Mastodon too:

![1743584722](https://user-images.githubusercontent.com/48640805/101272555-2cfeb480-3785-11eb-8487-46e3a035266e.png)
