### ISSUE TITLE
📝 Correction | About page: Riot is now Element

### ISSUE THREAD

**Issue by schwukas** [privacytools/privacytools.io#2150]
## Description

On the [about page](https://privacytools.io/about/) the mention of _Riot_ should be changed to _Element_ along with the URL that points to `https://riot.privacytools.io` that should point to `https://element.privacytools.io`.

I have a PR "ready" but I don't mind if someone else just goes in there and edits those few characters. Just let me know.

## Why I am making the suggestion

Because it's no longer up to date.

## My connection with the software

I'm using it.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
Go for it!
