### ISSUE TITLE
🆕 Software Suggestion |  Google Analytics Opt-out Browser Add-on

### ISSUE THREAD

**Issue by 97carmine** [privacytools/privacytools.io#2153]
## Basic Information

**Name:**  Google Analytics Opt-out Browser Add-on
**Category:** Browser extension
**URL:**  https://tools.google.com/dlpage/gaoptout?hl=

## Description

Extension that disables Google Analytics developed by Google

## Why I am making the suggestion

I don't really agree on how Google Analytics collects information and like me, there are probably more people.
And it seems like a good idea to share its existence

**Comment by freddy-m** [comment]
uBlock Origin already serves this function, and adding too many addons is bad for privacy.
