### ISSUE TITLE
📝 Correction | "Unfortunately the Android version of Firefox doesn't support managing tabs as containers." points to resolved bug

### ISSUE THREAD

**Issue by StoppingBuck** [privacytools/privacytools.io#2156]
## Description
On https://www.privacytools.io/browsers/#browser you write "Unfortunately the Android version of Firefox doesn't support managing tabs as containers." and link to this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1398097 which has been marked as resolved.

**Comment by dngray** [comment]
We should update that to point to https://github.com/stoically/temporary-containers/issues/465 instead as it's still not currently possible.
