### ISSUE TITLE
📝 Correction | https://www.privacytools.io/providers/dns/ - Uncensored DNS now supports DoH

### ISSUE THREAD

**Issue by gabeiam** [privacytools/privacytools.io#2158]
Uncensored DNS is marked with only supporting DoT, but they now support DoH. https://blog.uncensoreddns.org/blog/33-hello-to-dns-over-https-and-ecdsa-keys/

I was reading Uncensored DNS's blog and I saw they now offer DoH.

I am a user of uncensored DNS.

- [yes] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
Feel free to open a PR 🎉
