### ISSUE TITLE
📝 Correction | Remove 3 day free trial from IVPN description in the VPN Providers section

### ISSUE THREAD

**Issue by tacticalgeek** [privacytools/privacytools.io#2159]
## Description
The [3 day free trial](https://www.privacytools.io/providers/vpn/#ivpn) should be removed

## Why I am making the suggestion
3 day free trial is [not offered by IVPN ](https://www.ivpn.net/knowledgebase/billing/does-ivpn-offer-a-free-trial/)

## My connection with the software
None. Just wanted to try their service.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
Okay, they must have changed that.

**Comment by Gusted** [comment]
> Okay, they must have changed that.

> After a quick wayback machine trip I've found that it had been removed between [October 24th, 2020](https://web.archive.org/web/20201024085618/https://www.ivpn.net/pricing) and [November 26th, 2020](https://web.archive.org/web/20201126002358if_/https://www.ivpn.net/pricing).

Quoted from https://github.com/privacytools/privacytools.io/pull/2178#issue-548451144
