### ISSUE TITLE
❌ Software Removal | Qwant

### ISSUE THREAD

**Issue by ghost** [privacytools/privacytools.io#2160]
## Description
I propose the removal of Qwant.

## Why I am making the suggestion
In December 2020, Qwant blocked access from  Japan, Romania, Taiwan, and, Turkey.
I consider this to be a wicked act.

## My connection with the software
Former user of it.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
Sources? What were the reasons? Blocking access for some reason may be justified, it would help a little bit of context for this instead.

**Comment by romanholiday12** [comment]
> Sources? What were the reasons? Blocking access for some reason may be justified, it would help a little bit of context for this instead.

Several people are talking about it on Twitter, and with a VPN you can actually experience it for yourself.
I don't know why. The biggest problem with this is that Qwant has not released a reason or statement.

**Comment by LongJohn-Silver** [comment]
Well, then it wouldn't it be better to wait and see what they have to say?

**Comment by dngray** [comment]
Hmm.. can anyone actually get Qwant to work? I keep getting "No results found", for things I clearly should.

**Comment by freddy-m** [comment]
It has been working for me on Mobile @dngray

**Comment by dngray** [comment]
Okay, it seems to be lite.qwant.com that is broken for me. Regular qwant works though.

**Comment by rusty-snake** [comment]
> Well, then it wouldn't it be better to wait and see what they have to say?

https://twitter.com/QwantCom/status/1339149434572206080
https://nitter.net/QwantCom/status/1339149434572206080

**Comment by freddy-m** [comment]
See the comment above ^
