### ISSUE TITLE
🆕 Software Suggestion | Databunker

### ISSUE THREAD

**Issue by stremovsky** [privacytools/privacytools.io#2161]
## Basic Information

**Name:** Databunker
**Category:** software/cloud/
**URL:** https://databunker.org/

## Description

Databunker is a GDPR compliant user store service for Web and mobile apps. Databunker is a combination of several software concepts build together to provide PII storage and **privacy by design** out of the box:

* Personal identifiable information (PII) storage and vault
* Secure session storage for web applications
* Privacy portal for customers
* Application backend server
* DPO management tool
* Tokenization service
* Secret sauce

Databunker provides Nodejs examples for easy onboarding:

https://github.com/securitybunker/hello-nodejs-passport-js-magic-link-databunker

## Why I am making the suggestion

Originally I developed Databunker to help me to store customer data in a full GDPR compliant way. It grew to be a full-featured solution standing stringent privacy requirements.

## My connection with the software

I am a product author. Contact me at yuli@privacybunker.io for any questions.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by ph00lt0** [comment]
I don't think this is the right category for your software. I am also not sure if this is something for PTIO as this does not help a user seeking for ways to protect there own privacy. 
I think generally it is a interesting project, but it does not achieve as much as vaultproject.io.

**Comment by stremovsky** [comment]
Hi ph00lt0

Thank you for a quick reply.

Databunker has some similarities with the Hashicorp vault as it encrypts the records.
Instead of encryption of user passwords as in Hashicrop vault, Databunker encrypts user profile and
builds search index out of data found in the user profile (for example, email, login, phone) to allow
quick user record lookup. This index itself is built in a secure manner, so no actual plaintext is stored in a
backend database.

In addition, the product has an audit access log, track of changes, and many more features.

By generating a random password, Databunker allows, basically the end-user to login to his profile,
view his data, change the records, change consent agreements, etc...

This product helps organizations to help their own customers to control their own personal data and privacy.

BTW, here is a link to the latest presentation:
https://databunker.org/files/presentation.pdf

I would love to demo this tool.

Thanks,
Yuli
yuli@privacybunker.io

**Comment by lynn-stephenson** [comment]
@stremovsky It is an interesting project, but this is not part of PrivacyTools' target demographic.
