### ISSUE TITLE
📝 Correction | https://privacytools.io/browsers/#addons - Missing Microsoft Edge Add-ons links

### ISSUE THREAD

**Issue by griffedge** [privacytools/privacytools.io#2163]
## Description

The listings in [Recommended Browser Add-ons](https://privacytools.io/browsers/#addons) are missing the Microsoft Edge Add-ons links for [Decentraleyes](https://microsoftedge.microsoft.com/addons/detail/decentraleyes/lmijmgnfconjockjeepmlmkkibfgjmla) and [ClearURLs](https://microsoftedge.microsoft.com/addons/detail/clearurls/mdkdmaickkfdekbjdoojfalpbkgaddei).

## Why I am making the suggestion

By missing these links it is harder for users to access these tools in their browser of choice.

## My connection with the software

I occasionally use Microsoft Edge.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
Does Edge not use Google's addon store?

**Comment by ph00lt0** [comment]
Microsoft Edge is a privacy nightmare. Using Edge trying, while attempting to protect your privacy is doubtful on it's own.   https://www.scss.tcd.ie/Doug.Leith/pubs/browser_privacy.pdf
But since it's also there for the other add-ons it might be good to add it or remove it for the others.

**Comment by Mikaela** [comment]
@LongJohn-Silver Edge is capable of using the Chrome store, but it mainly points you to https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

**Comment by LongJohn-Silver** [comment]
Ooh, I see, they are building a little garden.

**Comment by freddy-m** [comment]
Feel free to open a PR!

**Comment by dngray** [comment]
Decentraleyes got removed in the latest PR, so i think we'll close this.
