### ISSUE TITLE
✨ Feature Suggestion | Signal and Phone Number

### ISSUE THREAD

**Issue by ghost** [privacytools/privacytools.io#2164]
## Description
If you recommend Signal, you should also recommend a privacy-conscious SMS provider.
If an SMS provider cannot be provided, then Signal should be removed.

**Comment by romanholiday12** [comment]
#1475 
#1868 
#2164

**Comment by ph00lt0** [comment]
This makes not a lot of sense to me. Your messages are encrypted in Signal. The only thing that would be exposed is the fact that you use it. If that is of concern there are many temporary phone number services, next to prepaid cards and VOIP.

**Comment by romanholiday12** [comment]
Temporary phone number services are often already used numbers.
To get a prepaid card, I need to have an ID in some countries.

Therefore, the recommendation of the VoIP service should be posted on PTIO.

**Comment by romanholiday12** [comment]
@ph00lt0 What VoIP service do you recommend?

**Comment by dngray** [comment]
Signal should be used with a number **that is not temporary**, otherwise a contact may end up messaging someone they didn't intend. We won't be recommending temporary number providers. We can't vet those and there's no assurance they won't sell the number to multiple people.

**Comment by romanholiday12** [comment]
> Signal should be used with a number **that is not temporary**, otherwise a contact may end up messaging someone they didn't intend. We won't be recommending temporary number providers. We can't vet those and there's no assurance they won't sell the number to multiple people.

I agree very much.
