### ISSUE TITLE
📝 Correction | Canary Mail

### ISSUE THREAD

**Issue by bcye** [privacytools/privacytools.io#2171]
## Description
Canary Mail is also available for Android and MacOS, but it's only listed for iOS currently.

## Why I am making the suggestion
n/a

## My connection with the software
N7a

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by bcye** [comment]
Source: https://canarymail.io/

**Comment by LongJohn-Silver** [comment]
AFAIK it is only listed for iOS because that is the best option in their garden, but it is not the best solution, K-9 is way better and it is libre, that is why it is recommended. Once some libre project is created for their platform Canary will probably be delisted. I would close this issue.

**Comment by bcye** [comment]
Good to know

**Comment by dngray** [comment]
Yes what @LongJohn-Silver said. While we do prefer open source recommendations, when none exist, options are limited.
