### ISSUE TITLE
🌐 Website Issue | <b> and <i> HTML elements

### ISSUE THREAD

**Issue by IacobusKopiirefuto** [privacytools/privacytools.io#2202]
## Description

Everywhere on the website `<strong>` and `<em>` HTML elements are consistently used. In just five cases `<i>` and `<b>` are used. Are they used in those cases on purpose as they are right elements for given part of the text, or should they rather be replaced with `<strong>` and `<em>`?

\
`grep -r '<b>'`:
```
privacytools.io/_includes/sections/browser-webrtc.html:<p>While software like NoScript prevents this, it's probably a good idea to
block this protocol directly as well, just to be safe. <b>Note:</b> This disables browser-based call functionality that is used for webapps like Discord, Hangouts, Jitsi, etc.</p>
privacytools.io/_includes/sections/browser-addons.html:  description="<strong>Snowflake</strong> is a new <a href=https://2019.www.torproject.org/docs/pluggable-transports.html.en>pluggable transport</a> from the Tor Project. If you have an uncensored connection, running this extension volunteers your connection to be used as a Snowflake proxy to help users unable to connect to the Tor network. Your IP will not be visible to the sites users visit using your proxy, as this extension will not make you an exit node. If your access to the Tor network is blocked, this extension will not assist you, and you should use the <a href=https://www.torproject.org>Tor Browser</a> instead. <b>Note:</b> This add-on does not work with WebRTC disabled."
```
\
`grep -r '<i>'`:
```
privacytools.io/pages/about/about.html:bio="I'm the moderator at r/Privacy and r/privacytoolsIO. Day to day, I am also – <i>irony alert</i> – an (ethical) digital marketer."
grep: privacytools.io/.git/objects/pack/pack-301480a2e49dfd3f51815512f370948bd845294c.pack: binary file matches
privacytools.io/_includes/sections/dns.html:  DNS-over-HTTPS, DNS-over-TLS, and DNSCrypt resolvers will not make you anonymous. Using Anonymized DNSCrypt hides <i>only</i> your DNS traffic from your Internet Service Provider. However, using any of these protocols will prevent DNS hijacking, and make your DNS requests harder for third parties to eavesdrop on and tamper with. If you are currently using Google's DNS resolver, you should pick an alternative here. See the <a href="#dns-definitions">definitions</a> below.
privacytools.io/_includes/team.html:      {% if include.bio %}<p class="card-text" itemprop="description">{{ include.bio | default: "<i>Hmm, this user hasn't written a bio quite yet :(</i>" }}</p>{% endif %}
```

I'm currently working on translation of PrivacyTools to Slovak language, so I'm noticing lots of minor stuff. I just thought I would ask. :-) 

According to Mozilla:
> The `<strong>` element is for content that is of greater importance, while the `<b>` element is used to draw attention to text without indicating that it's more important.
[`<strong>`: The Strong Importance element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong)

> The `<em>` element represents stress emphasis of its contents, while the `<i>` element represents text that is set off from the normal prose, such a foreign word, fictional character thoughts, or when the text refers to the definition of a word instead of representing its semantic meaning. (The title of a work, such as the name of a book or movie, should use `<cite>`.)
[`<em>`: The Emphasis element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em)

**Comment by dngray** [comment]
Hey just letting you know we'd love to accept a PR for this.
