### ISSUE TITLE
🆕 Software Suggestion | Drakkle

### ISSUE THREAD

**Issue by andresribeiro** [privacytools/privacytools.io#2207]
## Basic Information

**Name:** Drakkle
**Category:** Social Networks
**URL:** https://play.google.com/store/apps/details?id=com.andresribeiro.drakkle

## Description

Drakkle is a alternative to Twitter. With no ads, Drakkle promises to protect your privacy. It is under the laws of Brazil, then it is not under the 14 eyes

## Why I am making the suggestion

In my opinion it is a social network that deserves to be in the Privacy Tools

## My connection with the software

I am the creator of the software

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by Dyrimon** [comment]
I'm not a huge fan of their privacy policy, and they ask way too much permissions in their app.

### Permissions:

Calendar

    read calendar events plus confidential information
    add or modify calendar events and send email to guests without owners' knowledge

Contacts

    read your contacts

Location

    approximate location (network-based)
    precise location (GPS and network-based)

Phone

    read phone status and identity

Photos/Media/Files

    read the contents of your USB storage
    modify or delete the contents of your USB storage

Storage

    read the contents of your USB storage
    modify or delete the contents of your USB storage

Camera

    take pictures and videos

Microphone

    record audio

Wi-Fi connection information

    view Wi-Fi connections

Device ID & call information

    read phone status and identity

Other

    manage document storage
    receive data from Internet
    view network connections
    full network access
    change your audio settings
    run at startup
    draw over other apps
    control vibration
    prevent device from sleeping
    modify system settings
    install shortcuts
    read Google service configuration

### Privacy policy: (translated with DeepL)

Personal Information

To us, "personal information" is any and all types of information that can be used to directly identify someone (such as name, email, phone number). Any other information is not considered "personal information". All information collected is described in our Terms of Service and this Privacy Policy.

Anonymous Information

Any information that cannot be used to directly identify you (such as usage statistics of our services), is considered anonymous information.

How we receive your information

We may receive information from you when
- you provide it to us directly (such as when you create an account or contact us);
- We try to learn more about you when we collect certain data to provide you with a better experience (such as when we use your IP address to provide you with information tailored to your location, such as the language of our services, or when we use automatically collected statistics to try to understand how we can improve our services);

How we use your information

We use your information for the basic use of our services (such as showing your profile to other users), to improve our services through analysis and event logs (such as errors), and to provide you with a personalized service (such as adapting the language of our services)

Information shared with third parties

Some of your information may be shared with third parties who provide some type of service to us, such as a log and error analysis service. In addition, we may share information with third parties if:

- it is required by law;
- we believe it is necessary to prevent harm to you or someone else;

How your information is stored

All your information is stored on our servers, which may have been rented from third parties and are not necessarily located in our home country (Brazil). We take every precaution to ensure that your information is as secure as possible.

Changes to this Privacy Policy

This Privacy Policy may be changed at any time without notice. We will try to notify you when this happens.

Contact

Please feel free to contact us with any questions about our Privacy Policy at drakkle@protonmail.com

**Comment by dngray** [comment]
> Please feel free to contact us with any questions about our Privacy Policy at drakkle@protonmail.com

So they really couldn't afford to have a paid protonmail account, with a legit sounding email like say privacypolicy@example.com or support@example.com. The screenshots are rather laughable.
