### ISSUE TITLE
📝 Correction | Firefox Tweaks

### ISSUE THREAD

**Issue by putra995** [privacytools/privacytools.io#2213]
## Description
`dom.event.clipboardevents.enabled`

maybe need take note like "this can be recommend if you not using copy or paste feature on firefox" or something else

## Why I am making the suggestion

This tweak will **broke copy and paste feature** on firefox , so you can't using copy and paste feature

**Comment by freddy-m** [comment]
See #2081

**Comment by putra995** [comment]
thanks for answer @freddy-m :)
