### ISSUE TITLE
🆕 Software Suggestion | Blokada

### ISSUE THREAD

**Issue by paulverbeke** [privacytools/privacytools.io#2218]
## Basic Information

**Name:** Blokada
**Category:** DNS Provider: Encrypted DNS Client Recommendations for Android
**URL:** https://blokada.org/

## Description

Blokada is an open source adblocker and privacy oriented DNS client for Android and iOS.

## Why I am making the suggestion

I'm suggesting to put back Blokada here because as of version 5.0.10 the app now supports DNS over HTTPS. Many versions later it is now enabled by default. Blokada was removed because of a lack of encryption #1123.
But that's no longuer the case.
DoH is mentioned in [the changelog for 5.0.10](https://community.blokada.org/t/blokada-changelog-archive-before-2021/10279) but also in [their FAQ](https://blokada.org/#faq) and in the app itself
![Screenshot_20210227-001630](https://user-images.githubusercontent.com/6412153/109367835-81529580-7897-11eb-970e-cf546668b50f.jpg)
As said in #1123 Blokada is a very good adblocker, is themed as an adblocker contrary to Nebulo, is simple to use, and now does the job of both the current recommendations from this category "Android 9's built-in DNS-over-TLS resolver" and "Nebulo"

## My connection with the software

I have no connection with Blokada, I've just been using Blokada 5 a lot lately and noticed it was removed from here because of a lack of encryption.

- [ x ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by oldphones68** [comment]
Hello dear!
First to mention, this is my first ever comment on the GitHub. PLEASE PARDON ME IF IT GOES WRONG. PEOPLE FIRST TALK TO THEIR PARENTS WHEN THEY START SPEAKING. SO, I'M COMMENTING FIRST IN PRIVACYTOOLS IO COMMUNITY BECAUSE I LOVE THEM MORE,

Now, about your request ('issue' in the language of GitHub community, if I don't go wrong, you are requesting to add Blokada,
Here, I want to add that, I tried Blokada in some Xiaomi and Samsung devices BUT it was still showing ads.
I couldn't figure out why that happened.

So, I think, before adding Blokada some notes should be added about these such issues.

**Comment by freddy-m** [comment]
#1325

**Comment by paulverbeke** [comment]
Hi freddy-m,
I think I've read all I could find here on privacytools regarding Blokada, Nebulo, and Blokada delisting, and came to the conclusion that: 
Nebulo despite having most of the same functionality as Blokada isn't themed as an AdBlocker or TrackerBlocker and is more of an all-purpose DNS changer, with the steep learning curve coming with it. Nebulo on Google Play doesn't have any adblocker DNS by default because of Google policies. Blokada is much easier to use and click and start on fresh install.
AFAIK the only reason that went into delisting Blokada was the lack of encryption.

Just to let you know that this reason is now void.

**Comment by paulverbeke** [comment]
I need to add that after looking through the site, you're not advising any Android AdBlocker at system level.
Maybe this could be placed in [Android Privacy Add-ons](https://www.privacytools.io/operating-systems/#aaddons) ?
