### ISSUE TITLE
🆕 Software Suggestion | PrivacyWall

### ISSUE THREAD

**Issue by StoppingBuck** [privacytools/privacytools.io#2225]
## Basic Information

**Name:** PrivacyWall
**Category:** Search Engine
**URL:** https://www.privacywall.org/

## Description
These guys seem to be the new kid in town. They are offered as the default search engine on Samsung's new Galaxy S21 flagship phone, which - combined with their claims of being pro-privacy - suggests they might be worth investigating. If nothing else then because anyone who buys a new Samsung phone is going to assume that it's the privacy-aware choice because of the name lol.

## My connection with the software
Just bought a Samsung Galaxy S21 and noticed it as the default search engine choice. Never heard of it before, can't find any info online except for a very active, very irreverent reddit account (/u/privacywall)

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
I see little reason to list this given the other seach engines we list @privacytools/editorial

**Comment by ph00lt0** [comment]
This website connects to Zendesk (third party) without consent of user. Personally I have zero trust in Zendesk and see them as a privacy invasive company.
