### ISSUE TITLE
🆕 Resource Suggestion | DoINeedAVPN.com 

### ISSUE THREAD

**Issue by johnnyburnaway** [privacytools/privacytools.io#2241]
## Basic Information

**Name:** Do I need a VPN?
**Category:** VPN / Further Information resource
**URL:** https://www.doineedavpn.com / https://github.com/ivpn/doineedavpn.com

## Description

DoINeedAVPN.com helps people decide if they need a commercial VPN. The tool lists twenty-one privacy, security and anti-censorship concerns. It evaluates the combination of selections and recommends the use of commercial VPNs or alternative tools, where applicable. If the user picks issues that VPNs cannot solve, like hiding financial transactions, or stopping Facebook from tracking them, we steer them clear from using a commercial VPN service. We provide a detailed explanation for each selection, no matter if a VPN solves that issue or not.

## Why I am making the suggestion

The tools was inspired by an earlier blog post ['Why you don't need a VPN'](https://www.ivpn.net/blog/why-you-dont-need-a-vpn/). It was designed to push back against aggressive marketing and overselling by mainstream VPN services. Not everyone needs a VPN, and we could not find a tool to help experts help others navigate through these issues. The tool is open source and anyone can suggest improvements.

## My connection with the software

I'm one of the creators of this website and part of the IVPN team.  We deliberately don't recommend a VPN service on this site, rather show people independent and trustworthy resources for picking a VPN.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
I feel as though this is covered with [this](https://blog.privacytools.io/choosing-a-vpn/) blog post, and also [this](https://gist.github.com/joepie91/5a9909939e6ce7d09e29) which is mentioned on the site. Though I'd be interested to see what you think @privacytools/editorial

**Comment by nourkagha** [comment]
> Don't use free VPNs: your browsing data is the product that is being sold.

This could be misleading regarding ProtonVPN.

**Comment by GintokiHub** [comment]
I think it's a neat tool. 
However I'm not sure where this would be placed. 
And if it is offering all info. 
I wouldn't stand against it being placed however. 
Also the topic is already made a topic on the site. However putting this link below that section might have some merit>?

**Comment by freddy-m** [comment]
I'm going to close this issue (for reasons stated [here](https://github.com/privacytools/privacytools.io/issues/2241#issuecomment-804342185)), though wouldn't be against re-opening it in the future.
