### ISSUE TITLE
📝 Correction | Quad9 re-incorporated in Switzerland.

### ISSUE THREAD

**Issue by Sauron462** [privacytools/privacytools.io#2246]
Quad9 has stated they are now based in Sweden, and PTIO does not reflect this change.

Just wanted to let you guys know!

Source: https://quad9.net/news/blog/quad9-public-domain-name-service-moves-to-switzerland-for-maximum-internet-privacy-protection/

**Comment by freddy-m** [comment]
Feel free to open a PR!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Sauron462, this issue is a duplicate of issue #2212.

**Comment by freddy-m** [comment]
Duplicate of #2212.

Dealt with in #2214.
