### ISSUE TITLE
❌ Software Removal | Aether

### ISSUE THREAD

**Issue by pedohorse** [privacytools/privacytools.io#2253]
## Description

well, i mostly wanted for someone to confirm or dismiss my concerns about Aether

## Why I am making the suggestion

on the Aether site here https://getaether.net/dmca/
they state 
`If you send a DMCA request, and it is found to be valid, the content you’ve requested the Takedown for will be taken down from the servers Aether Technologies Inc. controls, if present, and a block will be placed on the identifier (“Fingerprint”) of the content, so that Aether clients will not download, make visible to the user, or share the fingerprinted content.`

this is literally plain censorship.
dmca as other "copyright laws" are  tools that can be abused even by individuals, not counting whole governments.

though the software is for now opensourced, and that means anyone can modify code to ignore those "fingerprints" - i doubt the majority of users will use anything but the one official client

## My connection with the software

no connection to this software, just a concerned citizen

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
Lol, that is not censorship, do you have an idea of how many libre projects would die if they would not comply to copyright laws? Even more, libre licenses are there exactly to do something similar, if someone uses your code without following the guidelines of your license you can ask a store to take down that project or sue the individual.

It is literally impossible except for pirate zones to not comply with DCMAs, and even in some cases torrent indexers remove that content, if you would like that to not exist don't conplain with this dev but with how capitalism works.

Regarding the "fingerprint" I imagine they refer to how a post/user is handled in the code, wich most probably translates into a string of numbers or letters, which is needed for the software to work.

**Comment by danarel** [comment]
Free software doesn't grant you permission to break the law, regardless of ones feelings towards a particular law. It's not censorship simply because they don't want to face legal consequences of their users. Though, here I am explaining laws to a pedophile horse.

**Comment by pedohorse** [comment]
@LongJohn-Silver true, that is not censorship YET. that is a tool for censorship, and how it is used is in hands of the project owners, and at this point - it's no different than twitter or similars. Your country is one bad election away from starting to abuse those laws, like some others do

@danarel hey! it's "children's horse"!

**Comment by LongJohn-Silver** [comment]
@pedohorse It is not in the hands of the project owner, it is in the hands of copyright holders, no one will DMCA you unless you are piracying, the only thing the developer can do is to accept the takedown or face legal consequences for their users' actions.

I do agree with you that the DMCA is an unjust law to benefit copyright lobbyists, but you are getting it all wrong and it is an off topic discussion for this.

**Comment by pedohorse** [comment]
well, i'm not specifically worried about DMCA - it doesn't even exist in some countries. I'm afraid of the fact that there is a way to dictate what is allowed what is not. Authoritarian governments have proven multiple times they will invent and use laws to take down any content they don't want online, all "perfectly legally".
So i was looking at aether as a government censorship resilient tool, which it clearly isn't (by multiple factors, including this one).
my mistake
