### ISSUE TITLE
📝 Correction | arkenfox

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [privacytools/privacytools.io#2258]
URL: https://blog.privacytools.io/firefox-privacy-an-introduction-to-safe/
search for: `ghacks user.js`<- two instances (same line)
change text to: `arkenfox user.js`
change hyperlink url to: https://github.com/arkenfox/user.js <- although the old one does redirect
complexity: none
priority: none
pants: optional
beers: always 🍻

**Comment by freddy-m** [comment]
Updated!
