### ISSUE TITLE
❌ Software Removal | OS with systemd 

### ISSUE THREAD

**Issue by claudiojulioferraz** [privacytools/privacytools.io#2261]
## Description

We must replace operating systems that use init Systemd for security reasons.
Read this article: https://unixsheikh.com/articles/the-real-motivation-behind-systemd.html

## Why I am making the suggestion

In summary Systemd should not be used because:
RedHat's hidden manipulations and intentions;
disregard for serious security bugs;
maybe the bugs are a backdoor.

The alternatives should be:
Debian -> Devuan
Ubuntu -> Trisquel
Arch -> Artix
Fedora -> PC Linux
NixOs -> Guix System
Ubuntu Touch ->  PostmarketOS
Tails and Whonix -> I don't know yet.

## My connection with the software
No connection to any cited software. 

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by lynn-stephenson** [comment]
We could consider alternatives, but there is no alternative to Whonix, and thus will _not_ be removed.

**Comment by dawidpotocki** [comment]
stoopid proposal

---

> Fact 1: systemd is from Red Hat

Oh no, goes who is developing your kernel?

> Fact 2: The primary reason for developing systemd is Red Hat's business interests in embedded devices

Who cares?

> Fact 3: No, it's not a myth, systemd is truly a huge monolith
> The fact is however, that many of these so-called individual binaries has functionality that simply will not work without other systemd components.

Well… not really, look at `elogind`. You will likely have use it on non-systemd Linux distros… oh wait… would that mean that you are using systemd? NOOOOOOOOOOOOO. Btw you do not have to use these systemd tools on a systemd systems.

> Fact 4: Privacy concerns
> systemd-resolved has hard coded fallback DNS servers for Cloudflare, Quad9 and Google. Even if you turn these off, a bug might cause these to be used anyway (which actually happened at one point).

They made this trade-off that in case your DNS server from DHCP is broken, it will fallback to something that will probably work, so you do not have a broken network connection. In case you did not know, bugs can happen everywhere.

---

Let's look at some links they listed

https://github.com/systemd/systemd/issues/6237

I do not see how it's an issue, you provided an invalid name so it ran it as a root, which is… the default and there is no other default possible that would make sense. You need a root privs to do that… so I really do not see the issue.

---

Most of this blog post is about Red Hat, not systemd as a software.

Now if we look at your alternatives…

- Devuan - takes a long timeeee to rebase on a new Debian release
- PC Linux - u want to replace Fedora with… a distro that is "So cool ice cubes are jealous" and a website looking like something straight from XP era or earlier?
- Trisquel - lmao
- postmarketOS - Did you ever use it? I have a PinePhone and pmOS is… not great.

---

And no… I'm not a Red Hat or systemd fanboy. I used Void Linux for over a year on my laptop and I'm using Alpine on my VPS. Runit it pretty simple and nice… but at some point you might notice that you need something more powerful and something that is more unified etc. Writing services for OpenRC is a pain in the ass, I hated every single moment of doing that. I could do what I wanted to do on systemd (I did not succeed on OpenRC) in a minute without any previous experience.

**Comment by rusty-snake** [comment]
Here's a list of projects in which RedHat has done a big part of development: https://en.wikipedia.org/wiki/Red_Hat#Programs_and_projects

- KVM 
- GNOME
- systemd
- PulseAudio
- LibreOffice
- Xorg

and even more:

- Linux (the kernel)
- NetworkManager
- Wayland
- Flatpak
- libvirt / virt-manager

There is no Linux w/o RedHat today.

**Comment by freddy-m** [comment]
See former team member @dawidpotocki's reply.
