### ISSUE TITLE
❌ Software Removal | Disroot

### ISSUE THREAD

**Issue by yuguamax** [privacytools/privacytools.io#2262]
## Description
I suggest the removal of Disroot.

## Why I am making the suggestion
Disroot is running a web server and an IMAP/SMTP server on the same computer.
This can be seen in the DNS records.
This is undesirable for security reasons.

## My connection with the software
No connection

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by Atavic** [comment]
Do you have any info about their LAN to support the idea that a web server and an IMAP/SMTP server run on the same host?

**Comment by lynn-stephenson** [comment]
This _potential_ issue should be reported to Disroot. But it's not likely you can prove that they are hosting _both_ on the same computer.
