### ISSUE TITLE
🆕 Software Suggestion | postale.io

### ISSUE THREAD

**Issue by yuguamax** [privacytools/privacytools.io#2266]
## Basic Information

**Name:** postale.io
**Category:** Email
**URL:** https://postale.io/

## Description
I suggest postale.io.
This is an email hosting service.
To use this, you need to prepare a separate domain.

## Why I am making the suggestion
This service does not seem to support MTA-STS.
However, mailbox.org also does not support MTA-STS if you use your own domain.

## My connection with the software
No connection

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by rusty-snake** [comment]
> #### Sub-processors
> 
> We use the following 3rd party services to improve, understand troubleshoot, report bugs and provide support for you:>
> 
> - Google Analytics
>    We use this service to understand general usage, traffic sources and to measure campaign success.
>  - Stripe
>    We use this service to handle all the payments made on the Service. The sole purpose is to increase security regarding the handle of sensible payments informations such as your credit cards details.
> 
> REMEMBER: We use these services only to provide you with a fantastic product that gives you easy access to things you like and to improve our general look and feel. If you choose to block, global opt out from some of the services that we use to deliver our product, you may run into errors, product bugs and other failures that influence your general experience and quality of our service. We are ok with that and respect your choice.

(https://postale.io/privacy-policy)

**Comment by freddy-m** [comment]
This provider does not fit our [criteria](https://www.privacytools.io/providers/email/#criteria), and accordingly it will not be listed.
