### ISSUE TITLE
❌ Software Removal | Disroot

### ISSUE THREAD

**Issue by goc980** [privacytools/privacytools.io#2285]
## Description
Disroot does not meet the Email Provider Criteria.

## Why I am making the suggestion
Disroot does not support MTA-STS and TLS-RPT.
The DMARC is broken.
https://www.hardenize.com/report/disr.it/1620291629

## My connection with the software
user

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
You are using incorrect addresses to test them.

**Comment by goc980** [comment]
@freddy-m You have strong authority. You need to investigate properly before closing it. Your work is sloppy.
