### ISSUE TITLE
❌ Software Removal | SimpleLogin

### ISSUE THREAD

**Issue by goc980** [privacytools/privacytools.io#2286]
## Description
SimpleLogin does not meet the Email Provider Criteria.

## Why I am making the suggestion
SimpleLogin does not support DNSSEC, MTA-STS, and TLS-RPT.
https://www.hardenize.com/report/aleeas.com/1620292470

## My connection with the software
user

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
You are using incorrect addresses to test them.

**Comment by MeMeBigProgrammer** [comment]
The address you have tested [(aleeas.com)](https://www.hardenize.com/report/aleeas.com/1620292470) is not the official address, which is [simplelogin.io](https://www.hardenize.com/report/simplelogin.io/1620031232)

The official address does meet the criteria.

**Comment by goc980** [comment]
> The address you have tested [(aleeas.com)](https://www.hardenize.com/report/aleeas.com/1620292470) is not the official address, which is [simplelogin.io](https://www.hardenize.com/report/simplelogin.io/1620031232)
> 
> The official address does meet the criteria.

You've probably never used SimpleLogin before.
This is the official address.
It is present by default in SimpleLogin.
You can find it by signing up.
