### ISSUE TITLE
🌐 Website Issue | "Tor Myths & FAQ" in "VPN Services" links to a Login Page

### ISSUE THREAD

**Issue by HarryHung** [privacytools/privacytools.io#2288]
When you click the "Tor Myths & FAQ" in the "[VPN Services](https://www.privacytools.io/providers/vpn/)" page, it links to a [login page of write.privacytools.io](https://write.privacytools.io/login?to=/my-thoughts-on-security/slicing-onions-part-1-myth-busting-tor).

## Screenshots
![image](https://user-images.githubusercontent.com/4848896/117550443-0a91ff80-b073-11eb-87eb-c59fd6d64848.png)
![image](https://user-images.githubusercontent.com/4848896/117550450-1382d100-b073-11eb-8a64-8dff0aef0d40.png)

**Comment by Dyrimon** [comment]
It seems the article is private now, if it needs login to view. Either that or @blacklight447-ptio deleted it.

**Comment by freddy-m** [comment]
At the moment, all write-freely blogs are private. Hopefully this will change soon.
