### ISSUE TITLE
🆕 Software Suggestion | Appwrite

### ISSUE THREAD

**Issue by christyjacob4** [privacytools/privacytools.io#2299]
## Basic Information

**Name: Appwrite**
**Category: Self-Hosted Backend**
**URL: https://github.com/appwrite/appwrite**

## Description
Appwrite is a self-hosted solution that provides developers with a set of easy-to-use and integrate REST APIs to manage their core backend needs.

## Why I am making the suggestion
We want to give developers a way to avoid boiler plate and focus on their app and also a provide them with a solid alternative to Firebase. 

## My connection with the software
I'm a maintainer of this project 
 
- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
Privacy Tools is focused on giving recommendations for end users, not developers, so I don't think they will aprove this.
