### ISSUE TITLE
🆕 Software Suggestion | Kleeppr

### ISSUE THREAD

**Issue by sandeepbele** [privacytools/privacytools.io#2305]
## Basic Information

**Name:** Kleeppr
**Category:** Email, Newsletter
**URL:** https://kleeppr.com

## Description
Kleeppr lets users subscribe to email newsletters without using personal or work email ids. On signup it creates random email and read-only inbox for a user. It provides a simple interface to browse, read newsletter feed and manage subscriptions. 

## Why I am making the suggestion
As newsletter scene exploded and became one of the primary sources of content, I grew more and more hesitant while giving away my personal email address to random mailing lists. So I created Kleeppr to solve my use case. Its simple concept and works well for newsletters and marketing emails (remember email coupon popups on virtually every e-commerce site). 

## My connection with the software
I am the author.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by ph00lt0** [comment]
This website runs in debug mode of Django. This is a security issue.

**Comment by sandeepbele** [comment]
@ph00lt0 Debug mode is off .. did you see something?..pls provide more info so that i can check

**Comment by rusty-snake** [comment]
> Kleeppr lets you subscribe to email newsletters anonymously.

![Screenshot_2021-05-26_06-03-19-fs8](https://user-images.githubusercontent.com/41237666/119610114-40134880-bde8-11eb-98ca-ec3999700d3b.png)

Where can I find the Privacy policy?

**Comment by sandeepbele** [comment]
@rusty-snake yes thats the link .. glad you found it!

**Comment by ph00lt0** [comment]
> @ph00lt0 Debug mode is off .. did you see something?..pls provide more info so that i can check

Previously when I tried searching it gave me the debug=true screen. I just tried again and now I get a normal Django CSRF bug page. 

As @rusty-snake points out your website contains many trackers/tracking cdn's which make it inconsiderable for PTIO.

**Comment by sandeepbele** [comment]
> > @ph00lt0 Debug mode is off .. did you see something?..pls provide more info so that i can check
> 
> Previously when I tried searching it gave me the debug=true screen. I just tried again and now I get a normal Django CSRF bug page.
> 
> As @rusty-snake points out your website contains many trackers/tracking cdn's which make it inconsiderable for PTIO.

Debug mode was never on. I am starting to suspect that you are making things up. 
Info @rusty-snake provided is from uBlock Origin, and apart from google analytics it did not flag anything. 

Kleeppr helps you interact with mailing lists without your personal email id. Let's first focus on that use case and its utility.

**Comment by LongJohn-Silver** [comment]
@sandeepbele Calm down a bit, I have seen them in other issues and they are not doing anything in bad faith.

IMO besides G Analalytics you also have connections to G Tag Manager and the rest of the connectios for them to work (G Static and google.com), plus the connection to CloudFlare might also be a concern for some, even if the rest of the project is awesome. SimpleLogin started the same way and now they don't have prorpietary dependancies anymore.

**Comment by ph00lt0** [comment]
>  Info @rusty-snake provided is from uBlock Origin, and apart from google analytics it did not flag anything.

@sandeepbele I can't review your setup man, I have definitely seen it and unfortunately can't provide you more info. 

I do consider bootstrapcdn, gstatic, netdna, and fontawesome as trackers as well.

**Comment by sandeepbele** [comment]
@ph00lt0 @rusty-snake @LongJohn-Silver Thank you for taking time and commenting. I will consider your feedback. Appreciate pointer to SimpleLogin, sounds like amazing service in similar spirit.

**Comment by LongJohn-Silver** [comment]
@sandeepbele It's nothing! If you want I can recommend some alternatives to those dependencies that are privacy respecting.

**Comment by sandeepbele** [comment]
@LongJohn-Silver Sure, that will be great!
