### ISSUE TITLE
📝 Correction | ProtonMail onion address

### ISSUE THREAD

**Issue by arche-dev** [privacytools/privacytools.io#2349]
## Description

ProtonMail has upgraded to a v3 onion address: https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/

from their old v2: https://protonirockerxow.onion/

## Why I am making the suggestion

Since v2 onions are being deprecated, and will go poof on October, it's going to be important to update the onion links so people won't be confused why the link isn't working.

## My connection with the software

No connections, just went to their site to check my email and found out they have a v3 now :<

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by Type-IIx** [comment]
What official ProtonMail source did you ostensibly get this link from? I have not seen their v3 address published anywhere.

Users should not use the above v3 onion link until official sources for this v3 onion are provided (tread carefully!)

**Comment by Type-IIx** [comment]
> ## Description
> 
> ProtonMail has upgraded to a v3 onion address: https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/
> 
> from their old v2: https://protonirockerxow.onion/
> ## Why I am making the suggestion
> 
> Since v2 onions are being deprecated, and will go poof on October, it's going to be important to update the onion links so people won't be confused why the link isn't working.
> ## My connection with the software
> 
> No connections, just went to their site to check my email and found out they have a v3 now :<
> 
>     * [x]  I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

What official ProtonMail source did you ostensibly get this link from? I have not seen their v3 address published anywhere.

Users should not use the above v3 onion link until official sources for this v3 onion are provided (tread carefully!)
