### ISSUE TITLE
❌ Software Removal | Frendica

### ISSUE THREAD

**Issue by ghost** [privacytools/privacytools.io#2355]
## Description
I propose the removal of Frendica.

## Why I am making the suggestion
The Frendica website does not support AEAD Cipher.
This means that the website cannot be viewed securely.
https://friendi.ca/

## My connection with the software
No connection
- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by samuel-lucas6** [comment]
The website uses HTTPS, so it seems that it can be viewed securely.

**Comment by rusty-snake** [comment]
I tried 6 server from https://dir.friendica.social/servers and ALL supported TLS 1.3.

[TLS 1.3 spec](https://datatracker.ietf.org/doc/html/rfc8446):

> Those that remain are all Authenticated Encryption with Associated Data (AEAD) algorithms.

**Comment by cookiepanda1** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=friendi.ca&s=217.197.80.132

**Comment by samuel-lucas6** [comment]
> 
> 
> https://www.ssllabs.com/ssltest/analyze.html?d=friendi.ca&s=217.197.80.132

It uses TLS 1.2 for me. It's really not great that it supports TLS 1.0 and 1.1 and doesn't support TLS 1.3, but TLS 1.2 is acceptable if configured properly and is still used by the majority of websites.

**Comment by cookiepanda1** [comment]
> > https://www.ssllabs.com/ssltest/analyze.html?d=friendi.ca&s=217.197.80.132
> 
> It uses TLS 1.2 for me. It's really not great that it supports TLS 1.0 and 1.1 and doesn't support TLS 1.3, but TLS 1.2 is acceptable if configured properly and is still used by the majority of websites.

Why do you keep going off topic?
I have a problem with the lack of AES-GCM (or Chacha20) in the cipher list.
I don't see the TLS version as a problem.

**Comment by cookiepanda1** [comment]
> This server does not support Authenticated encryption (AEAD) cipher suites.

https://www.ssllabs.com/ssltest/analyze.html?d=friendi.ca&s=217.197.80.132

**Comment by rusty-snake** [comment]
> I have a problem with the lack of AES-GCM (or Chacha20) in the cipher list.
I don't see the TLS version as a problem.

The cipher list has to do with the TLS version.

TLS 1.0 / TLS 1.1: unsecure
TLS 1.2: secure/unsecure (AES-GCM/ChaCha20/... and legacy ciphers)
TLS 1.3: secure (only secure ciphers)

> >  This server does not support Authenticated encryption (AEAD) cipher suites.
>
> https://www.ssllabs.com/ssltest/analyze.html?d=friendi.ca&s=217.197.80.132

It's only their homepage. Login is done on other servers.

@cookiepanda1 did you contacted friendica?

**Comment by samuel-lucas6** [comment]
@freddy-m I believe this issue can be closed.
