### ISSUE TITLE
🆕 Software Suggestion | Addition of Artix Linux OS

### ISSUE THREAD

**Issue by peepopoggers** [privacytools/privacytools.io#2364]
## Basic Information

**Name:** Artix Linux
**Category:** Operating Systems
**URL:** https://artixlinux.org/

## Description
It is based off of arch linux but has two major upsides:
* Systemd is removed and there are three options for replacement - runit, s6 and openrc.
* There is an easy-install GUI and you can choose display manager when downloading ISO.

Artix linux has created a sizable following and I feel it should get attention in the privacy community.

## Why I am making the suggestion

It is easy-to-use with gui and install and it is based on arch.
For what classification, I am personally unsure what it would be.
It seems a bit complex for introductory but a bit simple for advanced, so I want to hear some opinions.

## My connection with the software

I am a linux hobbyist that has experience with the software. It is a well-developed systemd-free alternative to arch linux

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Dont think this will be added see comments:

https://github.com/privacytools/privacytools.io/issues/2261

**Comment by peepopoggers** [comment]
> Dont think this will be added see comments:
> 
> #2261

I read that thread. This is not about removing systemd from ALL distros recommended, but recommending an arch-based systemd-free gui-install linux version that is gaining traction with a good reason.

**Comment by peepopoggers** [comment]
Also, I do not care about redhat owning systemd, its that systemd is a monolith in terms of control and having alternatives is always good to diversify.

On the privacy side of things, arch is one of the most versatile distributions but for new users it can be tedious if they have never touched a terminal before. Artix provides an install simple as ubuntu but also has a manual install for more advanced users. There is very low telemetry, if any, as far as I know.

**Comment by FriendlyRobotBird** [comment]
>It seems a bit complex for introductory but a bit simple for advanced, so I want to hear some opinions.

Yah I would agree with you on that. If there was ever an intermediate section added then maybe Artix could go there. 

I do have a question. Is there anything that Artix brings to the table besides not having Systemd? I feel like there are better Arch based distros to recommend if we go that route and most people don't consider systemd an issue. Also intermediate and advanced recommendations are not really as important as more seasoned Linux users will have the knowledge of picking a distro on their own without much help. The introductory section is much more important as beginners don't know any better and will most likely base their entire choice on it, in which case we want to make sure we did a good job recommending easy to use systems with good privacy.

**Comment by peepopoggers** [comment]
@FriendlyRobotBird
I don't think fundementally they are that different, but they have different init systems, so it adds to variety.

**Comment by dngray** [comment]
Whether something has systemd or does not it doesn't really impact privacy does it now.

One could argue that systemd-resolvd supports DoT (DNS over TLS) at an OS level meaning all lookups are over TLS, preventing casual eavesdropping.

What I will say is that systemd units tend to be more robust, than openrc init scripts.
