### ISSUE TITLE
🆕 Software Suggestion | Gentoo Linux

### ISSUE THREAD

**Issue by StefanCristian** [privacytools/privacytools.io#2368]
## Basic Information

**Name: Gentoo Linux**
**Category: Advanced Operating Systems**
**URL: https://www.gentoo.org/**

## Description

Gentoo Linux is a advanced source-based distribution that lets you easily manipulate all the packages and source in the system based on a automated package manager called Portage. You can easily access and modify the source code of all FOSS applications on your system with a centralized configuration, making Gentoo the ideal solution for understanding source of programs and their security, anonymity and privacy purpose.

## Why I am making the suggestion

The main reason is that Gentoo is the only **hardened by default** system from mainstream distributions. Hardened linuxes are by far better equipped to withstand cyber attacks compared to their non-hardened counterparts.

Another reason is that I am always suggesting for people to first understand the system in order to protect themselves. With useful knowledge, Gentoo being a source-based distribution you can compile it ( your whole system ) explicitly for privacy, security and anonymity, performance and hardened security.

One more crucial reason to support Gentoo as one of the top most important as security-focused distros is the ability to **remove** insecure/malicious sources from the system without impacting the packages or system itself, using a implementation called _USE flags_, which are part of the centralized configuration.

## My connection with the software

I am a very long time user of Gentoo, and as well as a maintainer of a Gentoo-based private security-focused distribution with some public tools.

**Comment by dngray** [comment]
> The main reason is that Gentoo is the only hardened by default 

Actually it isn't. You have to switch to a hardened profile and make some changes to your make.conf. One of the other issues with source based distributions is reproducible builds are basically impossible.

If a user wants to use Gentoo they likely don't need us to tell them that.

I say that as someone who does in fact use Gentoo for some things.

**Comment by StefanCristian** [comment]
> Actually it isn't. You have to switch to a hardened profile and make some changes to your make.conf. One of the other issues with source based distributions is reproducible builds are basically impossible.

Switching to a profile **is part** of the Gentoo installation process. Those options are available by default.
And reproducible builds are happening anyway when you have a binary repository already created via FEATURED configuration which **create** binary packages and a whole repository with it. Your builds **are** reproducible if you want to keep them.



> I say that as someone who does in fact use Gentoo for some things.

Since this is a issue of privacy and not personal usage, privacy has more priority. And Gentoo has that advantage that privacy can be built by default.
You are speaking in your personal name over this and disregard the necessity of knowledge.


> If a user wants to use Gentoo they likely don't need us to tell them that.

Yet in the same time there is also the need to tell new users that Gentoo **is also available as a privacy option**. Isn't this this whole site's idea?
