### ISSUE TITLE
📝 Correction | Tangible reason for Brave's removal

### ISSUE THREAD

**Issue by digitalblossom** [privacytools/privacytools.io#2372]
## Description
In the pull request for Brave's removal, there is a Reddit thread linked which was meant to poll the community on whether to remove or not. A lot of comments were advocating against the removal, citing an easier switch from Chrome to Brave for less tech-knowledgeable/people starting out and the lack of evidence for Brave being the ad centric company it is often made out to be.

## Why I am making the suggestion

I do not see a reason for its removal. Just because Mozilla is more trustworthy doesn't mean Brave shouldn't even be listed in the 'Worth Mentioning" section. After setting up both Brave and Firefox multiple times in accordance to the PTIO guide, Brave is easier to harden.

## My connection with the software

I use both Brave and Firefox

- [ ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment]
Please don't opne up new issues regarding old topics.
