### ISSUE TITLE
✨ Feature Suggestion | Chrome Privacy Tweaks

### ISSUE THREAD

**Issue by Super-Macintosh** [privacytools/privacytools.io#2376]
## Description
Create a Chrome Privacy Tweak section 

Disable OpenGL for video 
Set block third party cookie
Disable Privacy Sandbox
Disable chrome anti-virus and anti-phishing

And other

**Comment by LongJohn-Silver** [comment]
Trying to make Chrome private is pointless because doing would mean to strip it from all what it makes it Chrome, for which there are projects like ungoogled Chromium, which still is a bad idea because you are helping in them enforcing net centrality and browse the web in they way they want.

**Comment by Super-Macintosh** [comment]
Ok you didnt want help Chrome monopoly
Why you help firefox monopoly

**Comment by Super-Macintosh** [comment]
> Trying to make Chrome private is pointless because doing would mean to strip it from all what it makes it Chrome, for which there are projects like ungoogled Chromium, which still is a bad idea because you are helping in them enforcing net centrality and browse the web in they way they want.

Firefox is slow compared to Chrome if it's to have a slow browser and with a slow connection it's a horror

**Comment by rusty-snake** [comment]
> Ok you didnt want help Chrome monopoly
Why you help firefox monopoly

Where do you see a firefox monopole?

| Browser | StatCounter June 2021 | NetMarketShare May 2021 |
| - | - | - |
| Chrome | 68.76% | 69.57% |
| Edge | 8.39% | 12.16% |
| Safari | 9.70% | 3.45% |
| Firefox | 7.17% | 6.26% |

<sup>src: https://en.wikipedia.org/wiki/Usage_share_of_web_browsers</sup>

**Comment by Super-Macintosh** [comment]
> > Ok, vous ne vouliez pas d'aide au monopole de ChromePourquoi vous aidez le monopole de firefox
> 
> Où voyez-vous un monopole firefox ?
> 
> Navigateur	StatCounter juin 2021	NetMarketShare mai 2021
> Chrome	68,76 %	69,57 %
> Bord	8,39 %	12,16 %
> Safari	9,70 %	3,45 %
> Firefox	7,17 %	6,26 %
> src : [https://fr.wikipedia.org/wiki/Usage_share_of_web_browsers](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers)

If everyone uses firefox it will be the same

**Comment by samuel-lucas6** [comment]
I don't think it's necessary to provide privacy tweaks for Chromium based browsers when those browsers aren't being recommended. In contrast to the Windows 10 situation, there's generally no requirement to use a Chromium browser, although I have found it useful to have an alternate browser for when hardened Firefox breaks sites, so you could argue that something like the 'Don't use Windows 10' section should be added to the browser page for Chrome. Maybe that could link some further information.

> Firefox is slow compared to Chrome if it's to have a slow browser and with a slow connection it's a horror
> Chrome have lot of cool feature
> And i use Brave

I believe Chrome performs better on benchmarks, but when it comes to day-to-day usage, it's likely difficult to tell the difference. For instance, I just visited the sites I use most on Firefox and Brave, and some seemed to load faster on Brave and some on Firefox. I've also heard that both Chrome and Firefox use a high amount of RAM. However, with one tab open, Brave uses more than Firefox. Lastly, lots of these 'features' are frankly unnecessary or gimmicks. You shouldn't be storing passwords and card details in the browser, you shouldn't be syncing things to an account, and most people don't use multiple profiles. The best argument for using a Chromium based browser is security.

I use Brave sometimes as well, but I'm far from happy with the state of the browser, and the company is questionable. Similarly, I'm not a fan of Firefox, and Mozilla seems to be all over the place. They're both bloated and have bad default settings. There are currently no good browsers much like how there are no all around good privacy messengers, but something has to be recommended.

> If everyone uses firefox it will be the same

Firefox is not going to overtake Chrome.

**Comment by Super-Macintosh** [comment]
> I don't think it's necessary to provide privacy tweaks for Chromium based browsers when those browsers aren't being recommended. In contrast to the Windows 10 situation, there's generally no requirement to use a Chromium browser, although I have found it useful to have an alternate browser for when hardened Firefox breaks sites, so you could argue that something like the 'Don't use Windows 10' section should be added to the browser page for Chrome. Maybe that could link some further information.
> 
> > Firefox is slow compared to Chrome if it's to have a slow browser and with a slow connection it's a horror
> > Chrome have lot of cool feature
> > And i use Brave
> 
> I believe Chrome performs better on benchmarks, but when it comes to day-to-day usage, it's likely difficult to tell the difference. For instance, I just visited the sites I use most on Firefox and Brave, and some seemed to load faster on Brave and some on Firefox. I've also heard that both Chrome and Firefox use a high amount of RAM. However, with one tab open, Brave uses more than Firefox. Lastly, lots of these 'features' are frankly unnecessary or gimmicks. You shouldn't be storing passwords and card details in the browser, you shouldn't be syncing things to an account, and most people don't use multiple profiles. The best argument for using a Chromium based browser is security.
> 
> I use Brave sometimes as well, but I'm far from happy with the state of the browser, and the company is questionable. Similarly, I'm not a fan of Firefox, and Mozilla seems to be all over the place. They're both bloated and have bad default settings. There are currently no good browsers much like how there are no all around good privacy messengers, but something has to be recommended.
> 
> > If everyone uses firefox it will be the same
> 
> Firefox is not going to overtake Chrome.

My chrome doe 1s for youtube 3s firefox oof
We need to create a good browser
