### ISSUE TITLE
🆕 Software Suggestion | Retroshare

### ISSUE THREAD

**Issue by csoler** [privacytools/privacytools.io#2382]
## Basic Information

**Name:Retroshare**
**Category:file sharing, mail, forums, chat**
**URL:retroshare.cc**

## Description

I think that Retroshare (see retroshare.cc) should be mentioned on your website as it provides a wide range of secure services (mail, one-to-one chat, group chat, forums, file sharing, etc). I haven’t looked everywhere, but I don’t think I saw it. As an example, it totally contains the features of onionshare since it can optionally run on top of Tor.

## Why I am making the suggestion

Retroshare  creates a totally decentralized mesh of computers linked by authenticated TLS connections. It can run on top of TCP/UDP/Tor/I2P links. Tor management is built-in and doesn't need any specific configuration.

On top of the mesh it creates, Retroshare offers a few abstract data exchange systems: GXS (Generic eXchange System) which allows to spread information based on a subscription system, Turtle: a distant anonymous/authenticated tunneling system, Identities (some kind of pseudonyms, optionally linked to your node or anonymous) and circles to make groups out of them.

These abstract systems are used to create a bunch of services: mail, file sharing, forums, chat (one-to-one and IRC-like chat), channels, ... Retroshare also offers a plugin system that allows to create new services, and a JSON API that allows to talk to the running core using other languages (JS, python, etc) allowing to create applications on e.g. Android.

Privacy is guarantied beyond direct connections (a.k.a. friend nodes) on TCP/UDP links, and on direct connections on Tor/I2P links.

## My connection with the software

Being a developer of the software, I’ll be glad to answer any question regarding its level of security, the way it works, etc.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
Already mentioned under "worth mentioning" on https://www.privacytools.io/software/networks/
