### ISSUE TITLE
✨ Feature Suggestion | stop censorship

### ISSUE THREAD

**Issue by AcaiBerii** [privacytools/privacytools.io#2392]
## Description
lmao stop trying to protect protonmail lol stay mad  
https://privacy-watchdog.io/protonmail-devs-do-not-use-protonmail/  
https://privacy-watchdog.io/protonmails-criminal-history/  
https://privacy-watchdog.io/protonmails-creation-with-cia-nsa/

haha

**Comment by JakoonStick** [comment]
> I have prepared other people to continue posting all of the articles I have written.  I have arranged things so if someone tries to sue me in an attempt to censor the truth it will dramatically increase the attention the truth gets.
                                                                                                                                            - About page

Ohh i understand everything now, I'm laughing at you. 

The creator of that webpage disappeared- that should show how brave he is. Stay mad haha

**Comment by AcaiBerii** [comment]
> > I have prepared other people to continue posting all of the articles I have written.  I have arranged things so if someone tries to sue me in an attempt to censor the truth it will dramatically increase the attention the truth gets.
> > - About page
> 
> Ohh i understand everything now, I'm laughing at you.
> 
> The creator of that webpage disappeared- that should show how brave he is. Stay mad haha

did he only disappear because you harassed him?

**Comment by Dyrimon** [comment]
I think this can be locked to avoid further annoyances. @lynn-stephenson
