### ISSUE TITLE
🆕 Software Suggestion | Revolt

### ISSUE THREAD

**Issue by nourkagha** [privacytools/privacytools.io#2405]
## Basic Information

**Name:** Revolt
**Category:** Real-Time Communication
**URL:** https://revolt.chat

## Description

Revolt is a privacy-first, open source chat platform.

## Why I am making the suggestion

This is a very promising and upcoming privacy-friendly alternative to Discord. Element (Matrix) exists as a decentralised alternative, but Discord has its own design and niche which an extremely similar and more customisable platform like Revolt seems well capable of replacing. Having more chat platform options (including Signal) for a user to choose from depending on different use-cases and situations is always nice and healthy.

## My connection with the software

I have no affiliation or association with the software or its developers. I'm an enthusiastic early adopter who has for a long time wanted an open source, privacy/user-first chat platform similar or identical to Discord.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by youdontneedtoknow22** [comment]
In my opinion it still needs some time to mature, be used and audited. Currently it's not even end2end encrypted, it's on their roadmap tho.

**Comment by nourkagha** [comment]
I agree. It's still in closed beta. The purpose of this issue is just to put it on the radar and consolidate all current and future discussions.

**Comment by sif** [comment]
Do they say how they plan to differentiate themselves from Signal?

**Comment by freddy-m** [comment]
We won't add this yet, but may consider doing so in the future.
