### ISSUE TITLE
❌ Software Removal | LibreDNS

### ISSUE THREAD

**Issue by arche-dev** [privacytools/privacytools.io#2411]
## Description

LibreDNS doesn't support DNSSEC.

## Why I am making the suggestion

I was going to fix #2396 and I checked [CONTRIBUTING.md#dns](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md#dns), it looks like it requires DNSSEC to be listed and since LibreDNS doesn't have DNSSEC it should be removed.

## My connection with the software

Just a normal user 

- [x] I will keep the issue up-to-date if something I have said changes or I remember a cxnnection with the software.

**Comment by katzeprior** [comment]
How did you check that, last time i tried it it supported DNSSEC

**Comment by arche-dev** [comment]
> How did you check that, last time i tried it it supported DNSSEC

I don't know how to check directly, but https://gitlab.com/libreops/libredns/libredns-cfg/-/issues/3 would be an indicator that it doesn't support it, and https://dnscrypt.info/public-servers (page 3) also says that it doesn't support it.

**Comment by katzeprior** [comment]
Yeah should be removed then, also thanks for the list.

**Comment by freddy-m** [comment]
> CONTRIBUTING.md#dns

This page really needs to be updated. Or, even better, removed all together.
