### ISSUE TITLE
🆕 Software Suggestion | Web Torrent Checker

### ISSUE THREAD

**Issue by Loki-L1130** [privacytools/privacytools.io#2416]
## Basic Information

**Name:** Web Rorrent Checker
**Category:** Torrenting 
**URL:** https://checker.openwebtorrent.com/

## Description
This service help the users to check for Number of Seeds and Peers for a Torrent or a Magnet Link before Downloading

## Why I am making the suggestion

This would be great for Torrenting Users and also the project is Open-Source. Check it out here : https://github.com/alxhotel/webtorrent-checker

## My connection with the software

I have no connection with Software just a user of the Service

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
I doubt this will get added since this seems more related to privacy in piracy (which I'm all for it) but it's not the focus of Privacy Tools. Cool project, though!
