### ISSUE TITLE
✨ Feature Suggestion | Suggest switching away from Discord

### ISSUE THREAD

**Issue by lerichardson** [privacytools/privacytools.io#2423]
Discord isn't the best in privacy. They use Google Analytics, Google Cloud and collect more data then they have to (e.g. [Constantly contacting their "science" endpoint](https://twitter.com/trevorthalacker/status/1392502538453229572?s=20)) as well as not offering E2EE. 

I suggest adding discord to this list:
![Screenshot_20210905-182434.jpg](https://user-images.githubusercontent.com/72626657/132148113-34e8b5ad-6fb6-4f10-ab16-7987f0a2d35b.jpg)

**Comment by Dyrimon** [comment]
If you scroll down a bit You can find Discord in the [Team Chat Platforms](https://privacytools.io/software/real-time-communication/#teamchat)
