### ISSUE TITLE
❌ Software Removal | ProtonMail

### ISSUE THREAD

**Issue by papercore-dev** [privacytools/privacytools.io#2425]
## Description
I think that protonmail should be delisted, mainly due to browser fingerprint and IP address being sent to Swiss police.

## Why I am making the suggestion

- They broke their promise (left : before sending info to police / right : after sending info to police) [-> Here](https://i.imgur.com/BVx97Vk.png)
- People mention it as large scam scene.
- Representative said that true privacy is only possible in Tor and their privacy isn't secure after sending info to police.
- They proved these in this newsletter : [here](https://protonmail.com/blog/climate-activist-arrest/)

## My connection with the software

I was using ProtonMail and ProtonVPN for almost 2 years. I strongly recommended this service to my friends and it was once flawless but I saw this news and therefore I request software removal.
- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by infinitewaveparticle** [comment]
VPN services are treated differently under Swiss law and are not required to log any info and thus can't be forced by the courts to turn anything over. Your gripe with ProtonMail is legitimate though. I think they should move to a country that has privacy a friendly laws.

**Comment by katzeprior** [comment]
Maybe give the source of your claim?

**Comment by papercore-dev** [comment]
> VPN services are treated differently under Swiss law and are not required to log any info and thus can't be forced by the courts to turn anything over. Your gripe with ProtonMail is legitimate though. I think they should move to a country that has privacy-friendly laws.

Updated to ProtonVPN -> ProtonMail.

**Comment by papercore-dev** [comment]
> Maybe give the source of your claim?
> 
> https://protonmail.com/blog/climate-activist-arrest/

Thanks.

**Comment by youdontneedtoknow22** [comment]
What Promises did they broke?
It's mentioned in a 2014 blog post, which I read before creating my first account:

> The Internet is generally not anonymous, and if you are breaking Swiss law, a law-abiding company such as ProtonMail can be legally compelled to log your IP address

And it's even in your picture where they state: We have an anonymous email gateway. Well, that guy didn't use THE ANONYMOUS EMAIL GATEWAY and broke the french law and according to Switzerland he broke the swiss law, what do you think can Protonmail do for him?

**Comment by katzeprior** [comment]
I agree that protonmail did nothing wrong and is still one of the best options out there. Swiss laws are one of the best for an email provider.

**Comment by dngray** [comment]
Not going to happen, basically we don't know enough about the nature of this person's offenses yet. They clearly state they can be compelled to do IP logging, and if we removed a provider for this we'd have to remove all of them.

**Comment by infinitewaveparticle** [comment]
After reading their terms more closely I also agree that ProtonMail did nothing wrong... And that if it was nixed from the list for following the law, then all similar providers would have to be and we'd only be able to use services based in Antarctica or on Pluto or only ones based in tiny countries with extremely privacy-friendly laws.

Sent from ProtonMail mobile

-------- Original Message --------
