### ISSUE TITLE
💬 Discussion | Best set of filters list to protect privacy with ublock origin

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytools/privacytools.io#927]
I noticed that no filters list are recommended
```
https://www.privacytools.io/browsers/#addons
```

the default settings is not enough to protect privacy

**Comment by Atavic** [comment]
[Filterlists Repo](https://github.com/collinbarrett/FilterLists)
Select uBo under Software on filterlists.com

**Comment by atomGit** [comment]
> Select uBo under Software on filterlists.com

that results in over 200 pages of filters - ouch

[here's](https://12bytes.org/articles/tech/firefox/the-firefox-privacy-guide-for-dummies#neutering_the_wild_world_web_and_the_fox) what i run/suggest if the OP is interested - scroll down just a lil

**Comment by dngray** [comment]
Use the ones that are selected by default default selected. The others may break things.
